export const KEYWORDS: { label: string, detail: string, doc: string }[] = [
  {
    label: "ItemLevel",
    detail: "ItemLevel [Operator] <Level>",
    doc: "Numeric Level (0-100)\nThe item level the item was generated at."
  },
  {
    label: "DropLevel",
    detail: "DropLevel [Operator] <Level>",
    doc: "Numeric Level (0-100)\n	The level that the item starts dropping at."
  },
  {
    label: "Quality",
    detail: "Quality [Operator] <Quality>",
    doc: "Numeric Quality (0-20)\nThe amount of quality on the item."
  },
  {
    label: "Rarity",
    detail: "Rarity [Operator] <Rarity>",
    doc: "Normal, Magic, Rare, Unique	\nRarity of the item."
  },
  {
    label: "Class",
    detail: "Class	<Class>",
    doc: "Full or partial item class name	The item class. \nSpecifying part of a class name is allowed and will match any classes with that text in the name. So for example \"One Hand\" will match both \"One Hand Sword\" and \"One Hand Axe\""
  },
  {
    label: "BaseType",
    detail: "BaseType <Type>",
    doc: "Full or partial item name	The base type of the item. \nSpecifying a part of a base type name is allowed and will match any of the base types with that text in the name."
  },
  {
    label: "Prophecy",
    detail: "Prophecy <Type>",
    doc: "Full or partial prophecy name	The prophecy name. \nSpecifying a part of a prophecy name is allowed and will match any of the prophecies with that text in the name. Prophecies have the Class type \"Stackable Currency\"."
  },
  {
    label: "Sockets",
    detail: "Sockets [Operator] <Sockets>",
    doc: "Numeric Number of Sockets (0-6)	\nTotal number of sockets that the item has."
  },
  {
    label: "LinkedSockets",
    detail: "LinkedSockets [Operator] <Links>",
    doc: "Numeric Number of Links (0-6)	\nThe size of the largest group of linked sockets that the item has."
  },
  {
    label: "SocketGroup",
    detail: "SocketGroup [Group]",
    doc: "R, G, B, W	\nA group of linked sockets that contains the specified combination. Each letter is short-hand for the colour (i.e. Red = R). For example, RRG will match any group that contains two red sockets linked with a green socket."
  },
  {
    label: "Height",
    detail: "Height [Operator] <Value>",
    doc: "Numeric number of slots (1-4)	\nThe number of slots the item takes on the Y-axis (verical axis), i.e. the height of the item."
  },
  {
    label: "Width",
    detail: "Width [Operator] <Value>",
    doc: "Numeric number of slots (1-2)	\nThe number of slots the item takes on the X-axis (horizontal axis), i.e. the width of the item."
  },
  {
    label: "HasExplicitMod",
    detail: "HasExplicitMod <Value>",
    doc: "Full or partial item name	Filter by mods on an item by name. \nFor example: [HasExplicitMod \"Tyrannical\" ] (Tyrannical=Local Physical Damage 155 to 169%)"
  },
  {
    label: "AnyEnchantment",
    detail: "AnyEnchantment <Boolean>",
    doc: "True or False	\nIf an item has any enchantment."
  },
  {
    label: "HasEnchantment",
    detail: "HasEnchantment <Value>",
    doc: "Full or partial name of enchantment	\nFilter by enchantments."
  },
  {
    label: "StackSize",
    detail: "StackSize [Operator] <Value>",
    doc: "Numeric number of slots (1-n)	\nCurrency stack size."
  },
  {
    label: "GemLevel",
    detail: "GemLevel [Operator] <Value>",
    doc: "Numeric number of slots (1-21)	\nGem Level."
  },
  {
    label: "Identified",
    detail: "Identified <Boolean>",
    doc: "True or False	\nIf an item is identified or not."
  },
  {
    label: "Corrupted",
    detail: "Corrupted <Boolean>",
    doc: "True or False	\nIf an item is corrupted or not."
  },
  {
    label: "ElderItem",
    detail: "ElderItem <Boolean>",
    doc: "True or False	\nIf an item is an Elder item or not."
  },
  {
    label: "ShaperItem",
    detail: "ShaperItem <Boolean>",
    doc: "True or False	\nIf an item is a Shaper item or not."
  },
  {
    label: "FracturedItem",
    detail: "FracturedItem <Boolean>",
    doc: "True or False	\nIf an item is fractured or not."
  },
  {
    label: "SynthesisedItem",
    detail: "SynthesisedItem <Boolean>",
    doc: "True or False	\nIf an item is synthesised or not."
  },
  {
    label: "ShapedMap",
    detail: "ShapedMap <Boolean>",
    doc: "True or False	\nIf the map is shaped or not."
  },
  {
    label: "MapTier",
    detail: "MapTier [Operator] <Value>",
    doc: "Numeric Tier (1-17)	\nThe map tier of the map."
  },
  {
    label: "SetBorderColor",
    detail: "SetBorderColor <Red> <Green> <Blue> [Alpha]",
    doc: "0-255	\nSets the border colour of the item box in RGB values from 0-255 with optional Alpha (opacity) value of 0-255."
  },
  {
    label: "SetTextColor",
    detail: "SetTextColor <Red> <Green> <Blue> [Alpha]",
    doc: "0-255	\nSets the text colour of the item box in RGB values from 0-255 with optional Alpha (opacity) value of 0-255."
  },
  {
    label: "SetBackgroundColor",
    detail: "SetBackgroundColor <Red> <Green> <Blue> [Alpha]",
    doc: "0-255	\nSets the colour of the item box in RGB values from 0-255 with optional Alpha (opacity) value of 0-255."
  },
  {
    label: "SetFontSize",
    detail: "SetFontSize <FontSize>",
    doc: "18-45 (default: 32)	\nSets the font-size of item text."
  },
  {
    label: "PlayAlertSound",
    detail: "PlayAlertSound <Id> [Volume]",
    doc: "1-? [0-300]	\nPlays the specified Alert Sound with optional volume when dropped. Only one sound can be played at a time."
  },
  {
    label: "PlayAlertSoundPositional",
    detail: "PlayAlertSoundPositional <Id> [Volume]",
    doc: "1-? [0-300]	\nPlays the specified Alert Sound with optional volume when dropped. Only one sound can be played at a time."
  },
  {
    label: "DisableDropSound",
    detail: "",
    doc: "Disable the drop sound (undocumented feature)."
  },
  {
    label: "CustomAlertSound",
    detail: "CustomAlertSound <FileName/FilePath>",
    doc: "local path to the filter file OR absolute path	\nPlays the specified custom sound when a specified item drops. (almost all of the common file extensions should be supported)"
  },
  {
    label: "MinimapIcon",
    detail: "MinimapIcon <Size> <Color> <Shape>",
    doc: "* Size: 0 (largest), 1 (medium), 2 (small)\n" +
      "* Color: Red, Green, Blue, Brown, White, Yellow\n" +
      "* Shape: Circle, Diamond, Hexagon, Square, Star, Triangle\n" +
      "Displays an icon on the minimap for specified items."
  },
  {
    label: "PlayEffect",
    detail: "PlayEffect <Color> [Temp]	",
    doc: "Red, Green, Blue, Brown, White, Yellow	\nDisplays a coloured beam of light above an item highlighted by an item filter.\nUse the Temp parameter to have a beam only appear as the item drops.\nOtherwise, it will be permanently visible."
  },
];

export const BOOLEAN: string[] = [
  "True",
  "False"
]

export const EFFECTS: string[] = [
  "Red",
  "Green",
  "Blue",
  "Brown",
  "White",
  "Yellow"
]

export const ICON_SIZE: string[] = [
  "0",
  "1",
  "2"
]

export const ICON_COLORS: string[] = [
  "Red",
  "Green",
  "Blue",
  "Brown",
  "White",
  "Yellow"
]

export const ICON_SHAPES: string[] = [
  "Circle",
  "Diamond",
  "Hexagon",
  "Square",
  "Star",
  "Triangle"
]

export const CLASSES: string[] = [
  "LifeFlask",
  "ManaFlask",
  "HybridFlask",
  "Currency",
  "Stackable Currency",
  "Amulet",
  "Ring",
  "Claw",
  "Dagger",
  "Wand",
  "One Hand Sword",
  "Thrusting One Hand Sword",
  "One Hand Axe",
  "One Hand Mace",
  "Bow",
  "Staff",
  "Two Hand Sword",
  "Two Hand Axe",
  "Two Hand Mace",
  "Active Skill Gem",
  "Support Skill Gem",
  "Quiver",
  "Belt",
  "Gloves",
  "Boots",
  "Body Armour",
  "Helmet",
  "Shield",
  "Sceptre",
  "UtilityFlask",
  "Map",
  "MapFragment",
  "Microtransaction",
  "Jewel",
  "DivinationCard",
  "MiscMapItem",
  "Leaguestone",
  "UniqueFragment",
  "AbyssJewel"
];

export const RARITIES: string[] = [
  "Normal",
  "Magic",
  "Rare",
  "Unique"
];

export const PROPHECIES: string[] = [
  //Master missions
  "A Master Seeks Help",

  //Crafting
  "A Valuable Combination",
  "Fated Connections",
  "Golden Touch",
  "Resistant to Change",
  "Smothering Tendrils",
  "The Beautiful Guide",
  "The Hardened Armour",
  "The Jeweller's Touch",
  "The Sharpened Blade",
  "Touched by the Wind",
  "Trash to Treasure",
  "Twice Enchanted",
  "Vital Transformation",

  //Fated Uniques
  "A Dishonourable Death",
  "A Forest of False Idols",
  "A Rift in Time",
  "A Vision of Ice and Fire",
  "Agony at Dusk",
  "Ancient Doom",
  "Battle Hardened",
  "Black Devotion",
  "Blind Faith",
  "Blinding Light",
  "Burning Dread",
  "Cold Blooded Fury",
  "Cold Greed",
  "Crimson Hues",
  "Dance of Steel",
  "Dark Instincts",
  "Darktongue's Shriek",
  "Dying Cry",
  "End of the Light",
  "Faith Exhumed",
  "Fire and Brimstone",
  "Fire and Ice",
  "From The Void",
  "Greed's Folly",
  "Heavy Blows",
  "Last of the Wildmen",
  "Mouth of Horrors",
  "Nature's Resilience",
  "Pleasure and Pain",
  "Power Magnified",
  "Severed Limbs",
  "Song of the Sekhema",
  "Sun's Punishment",
  "The Apex Predator",
  "The Beginning and the End",
  "The Bishop's Legacy",
  "The Bloody Flowers Redux",
  "The Bowstring's Music",
  "The Dreaded Rhoa",
  "The Fall of an Empire",
  "The Flow of Energy",
  "The Great Leader of the North",
  "The Great Mind of the North",
  "The Karui Rebellion",
  "The King and the Brambles",
  "The King's Path",
  "The Malevolent Witch",
  "The Mentor",
  "The Misunderstood Queen",
  "The Nightmare Awakens",
  "The Queen's Sacrifice",
  "The Servant's Heart",
  "The Silverwood",
  "The Snuffed Flame",
  "The Storm Spire",
  "Trapped in the Tower",
  "Winter's Mournful Melodies",

  //Tempest
  "Crushing Squall",
  "Fire from the Sky",
  "Ice from Above",
  "Lightning Falls",
  "The Undead Storm",
  "Vaal Winds",

  //Encounter
  "A Call into the Void",
  "A Firm Foothold",
  "A Prodigious Hand",
  "A Whispered Prayer",
  "Abnormal Effulgence",
  "Against the Tide",
  "Baptism by Death",
  "Blood in the Eyes",
  "Blood of the Betrayed",
  "Cleanser of Sins",
  "Custodians of Silence",
  "Fear's Wide Reach",
  "Fire, Wood and Stone",
  "Flesh of the Beast",
  "From Death Springs Life",
  "Graceful Flames",
  "Heart of the Fire",
  "Lost in the Pages",
  "Nemesis of Greed",
  "Notched Flesh",
  "Roth's Legacy",
  "Storm on the Horizon",
  "Storm on the Reef",
  "Strong as a Bull",
  "The Brutal Enforcer",
  "The Eagle's Cry",
  "The Flayed Man",
  "The Hollow Pledge",
  "The Lady in Black",
  "The Last Watch",
  "The Lost Undying",
  "The Mysterious Gift",
  "The Nest",
  "The Petrified",
  "The Prison Guard",
  "The Prison Key",
  "The Queen's Vaults",
  "The Singular Spirit",
  "The Sinner's Stone",
  "The Soulless Beast",
  "The Stockkeeper",
  "The Sword King's Passion",
  "The Vanguard",
  "The Walking Mountain",
  "The Ward's Ward",
  "The Watcher's Watcher",
  "Weeping Death",
  "Wind and Thunder",

  //Currencies
  "A Regal Death",
  "Erased from Memory",
  "Lasting Impressions",
  "Overflowing Riches",
  "Pools of Wealth",
  "Reforged Bonds",
  "The Alchemist",
  "The Corrupt",
  "The God of Misfortune",

  //Nothing
  "An Unseen Peril",
  "Deadly Twins",
  "Defiled in the Sceptre",
  "Echoes of Witchcraft",
  "Ending the Torment",
  "Fallow At Last",
  "Forceful Exorcism",
  "Hidden Reinforcements",
  "Hidden Vaal Pathways",
  "Holding the Bridge",
  "In the Grasp of Corruption",
  "Living Fires",
  "Monstrous Treasure",
  "Mysterious Invaders",
  "Mysterious Invaders",
  "Mysterious Invaders",
  "Mysterious Invaders",
  "Mysterious Invaders",
  "Path of Betrayal",
  "Plague of Frogs",
  "Plague of Rats",
  "Possessed Foe",
  "Rebirth",
  "Risen Blood",
  "Soil, Worms and Blood",
  "The Brothers of Necromancy",
  "The Child of Lunaris",
  "The Cursed Choir",
  "The Forgotten Garrison",
  "The Forgotten Soldiers",
  "The Four Feral Exiles",
  "The Hungering Swarm",
  "The Invader",
  "The Trembling Earth",
  "The Twins",
  "The Undead Brutes",
  "Undead Uprising",
  "Unnatural Energy",
  "Vaal Invasion",
  "Visions of the Drowned",
  "Waiting in Ambush",

  //Others
  "Bountiful Traps",
  "Erasmus' Gift",
  "Gilded Within",
  "Hunter's Lesson",
  "Kalandra's Craft",
  "The Dream Trial",
  "The Dreamer's Dream",
  "The Fortune Teller's Collection",
  "The Lost Maps",
  "The Scout",
  "The Wealthy Exile",

  //Chains
  "Anarchy's End I",
  "Anarchy's End II",
  "Anarchy's End III",
  "Anarchy's End IV",
  "Ancient Rivalries I",
  "Ancient Rivalries II",
  "Ancient Rivalries III",
  "Ancient Rivalries IV",
  "Beyond Sight I",
  "Beyond Sight II",
  "Beyond Sight III",
  "Beyond Sight IV",
  "Day of Sacrifice I",
  "Day of Sacrifice II",
  "Day of Sacrifice III",
  "Day of Sacrifice IV",
  "Deadly Rivalry I",
  "Deadly Rivalry II",
  "Deadly Rivalry III",
  "Deadly Rivalry IV",
  "Deadly Rivalry V",
  "Thaumaturgical History I",
  "Thaumaturgical History II",
  "Thaumaturgical History III",
  "Thaumaturgical History IV",
  "The Ambitious Bandit I",
  "The Ambitious Bandit II",
  "The Ambitious Bandit III",
  "The Feral Lord I",
  "The Feral Lord II",
  "The Feral Lord III",
  "The Feral Lord IV",
  "The Feral Lord V",
  "The Plaguemaw I",
  "The Plaguemaw II",
  "The Plaguemaw III",
  "The Plaguemaw IV",
  "The Plaguemaw V",
  "The Unbreathing Queen I",
  "The Unbreathing Queen II",
  "The Unbreathing Queen III",
  "The Unbreathing Queen IV",
  "The Unbreathing Queen V",
  "The Warmongers I",
  "The Warmongers II",
  "The Warmongers III",
  "The Warmongers IV",
  "Unbearable Whispers I",
  "Unbearable Whispers II",
  "Unbearable Whispers III",
  "Unbearable Whispers IV",
  "Unbearable Whispers V"
];

export const ENCHANTMENTS: string[] = [
  "Enchantment Word of Blades",
  "Enchantment Edict of Blades",
  "Enchantment Decree of Blades",
  "Enchantment Commandment of Blades",
  "Enchantment Word of Flames",
  "Enchantment Edict of Flames",
  "Enchantment Decree of Flames",
  "Enchantment Commandment of Flames",
  "Enchantment Word of Force",
  "Enchantment Edict of Force",
  "Enchantment Decree of Force",
  "Enchantment Commandment of Force",
  "Enchantment Word of Frost",
  "Enchantment Edict of Frost",
  "Enchantment Decree of Frost",
  "Enchantment Commandment of Frost",
  "Enchantment Word of Fury",
  "Enchantment Edict of Fury",
  "Enchantment Decree of Fury",
  "Enchantment Commandment of Fury",
  "Enchantment Word of Inferno",
  "Enchantment Edict of Inferno",
  "Enchantment Decree of Inferno",
  "Enchantment Commandment of Inferno",
  "Enchantment Word of Ire",
  "Enchantment Edict of Ire",
  "Enchantment Decree of Ire",
  "Enchantment Commandment of Ire",
  "Enchantment Word of Light",
  "Enchantment Edict of Light",
  "Enchantment Decree of Light",
  "Enchantment Commandment of Light",
  "Enchantment Word of Reflection",
  "Enchantment Edict of Reflection",
  "Enchantment Decree of Reflection",
  "Enchantment Commandment of Reflection",
  "Enchantment Word of Spite",
  "Enchantment Edict of Spite",
  "Enchantment Decree of Spite",
  "Enchantment Commandment of Spite",
  "Enchantment Word of the Tempest",
  "Enchantment Edict of the Tempest",
  "Enchantment Decree of the Tempest",
  "Enchantment Commandment of the Tempest",
  "Enchantment Word of the Grave",
  "Enchantment Edict of the Grave",
  "Enchantment Decree of the Grave",
  "Enchantment Commandment of the Grave",
  "Enchantment Word of Thunder",
  "Enchantment Edict of Thunder",
  "Enchantment Decree of Thunder",
  "Enchantment Commandment of Thunder",
  "Enchantment Word of War",
  "Enchantment Edict of War",
  "Enchantment Decree of War",
  "Enchantment Commandment of War",
  "Enchantment Word of Winter",
  "Enchantment Edict of Winter",
  "Enchantment Decree of Winter",
  "Enchantment Commandment of Winter",
  "Enchantment Chaos Damage 1",
  "Enchantment Chaos Damage 2",
  "Enchantment Chaos Damage 3",
  "Enchantment Fire Damage 1",
  "Enchantment Fire Damage 2",
  "Enchantment Fire Damage 3",
  "Enchantment Attack and Cast Speed 1",
  "Enchantment Attack and Cast Speed 2",
  "Enchantment Attack and Cast Speed 3",
  "Enchantment Status Ailments 1",
  "Enchantment Status Ailments 2",
  "Enchantment Status Ailments 3",
  "Enchantment Cold Damage 1",
  "Enchantment Cold Damage 2",
  "Enchantment Cold Damage 3",
  "Enchantment Critical Strike Chance 1",
  "Enchantment Critical Strike Chance 2",
  "Enchantment Critical Strike Chance 3",
  "Enchantment Attack Dodge 1",
  "Enchantment Attack Dodge 2",
  "Enchantment Attack Dodge 3",
  "Enchantment Elemental Penetration 1",
  "Enchantment Elemental Penetration 2",
  "Enchantment Elemental Penetration 3",
  "Enchantment Leech 1",
  "Enchantment Leech 2",
  "Enchantment Leech 3",
  "Enchantment Regeneration 1",
  "Enchantment Regeneration 2",
  "Enchantment Regeneration 3",
  "Enchantment Lightning Damage 1",
  "Enchantment Lightning Damage 2",
  "Enchantment Lightning Damage 3",
  "Enchantment Mana Cost 1",
  "Enchantment Mana Cost 2",
  "Enchantment Mana Cost 3",
  "Enchantment Movement Speed 1",
  "Enchantment Movement Speed 2",
  "Enchantment Movement Speed 3",
  "Enchantment Spell Dodge 1",
  "Enchantment Spell Dodge 2",
  "Enchantment Spell Dodge 3",
  "Enchantment Stun Avoidance 1",
  "Enchantment Stun Avoidance 2",
  "Enchantment Stun Avoidance 3",
  "Armageddon Brand Attached Target Fire Penetration 1",
  "Armageddon Brand Attached Target Fire Penetration 2",
  "Armageddon Brand Repeat Frequency 1",
  "Armageddon Brand Repeat Frequency 2",
  "Enchantment Abyssal Cry Damage 1",
  "Enchantment Abyssal Cry Damage 2",
  "Enchantment Abyssal Cry Duration 1",
  "Enchantment Abyssal Cry Duration 2",
  "Enchantment Ancestral Protector Attack Speed 1",
  "Enchantment Ancestral Protector Attack Speed 2",
  "Enchantment Ancestral Protector Damage 1",
  "Enchantment Ancestral Protector Damage 2",
  "Enchantment Ancestral Protector Resistances 1",
  "Enchantment Ancestral Protector Resistances 2",
  "Enchantment Ancestral Protector Placement Speed 1",
  "Enchantment Ancestral Protector Placement Speed 2",
  "Enchantment Ancestral Warchief Damage 1",
  "Enchantment Ancestral Warchief Damage 2",
  "Enchantment Ancestor Warchief Melee Damage 1",
  "Enchantment Ancestor Warchief Melee Damage 2",
  "Enchantment Ancestor Warchief Area Of Effect 1",
  "Enchantment Ancestor Warchief Area Of Effect 2",
  "Enchantment Anger Reservation 1",
  "Enchantment Anger Reservation 2",
  "Enchantment Animate Guardian Damage 1",
  "Enchantment Animate Guardian Damage 2",
  "Enchantment Animate Guardian Elemental Resistances 1",
  "Enchantment Animate Guardian Elemental Resistances 2",
  "Enchantment Animate Weapon Chance To Create Additional Copy 1",
  "Enchantment Animate Weapon Chance To Create Additional Copy 2",
  "Enchantment Animate Weapon Damage 1",
  "Enchantment Animate Weapon Damage 2",
  "Enchantment Animate Weapon Duration 1",
  "Enchantment Animate Weapon Duration 2",
  "Enchantment Arc Damage 1",
  "Enchantment Arc Damage 2",
  "Enchantment Arc Damage Per Chain 1",
  "Enchantment Arc Damage Per Chain 2",
  "Enchantment Arc Num Of Additional Projectiles In Chain 1",
  "Enchantment Arc Shock Chance 1",
  "Enchantment Arc Shock Chance 2",
  "Enchantment Arctic Armour Buff Effect 1",
  "Enchantment Arctic Armour Buff Effect 2",
  "Enchantment Arctic Armour Mana Reservation 1",
  "Enchantment Arctic Armour Mana Reservation 2",
  "Enchantment Arctic Breath Chilling Area Movement Velocity 1",
  "Enchantment Arctic Breath Damage 1",
  "Enchantment Arctic Breath Damage 2",
  "Enchantment Arctic Breath Duration 1",
  "Enchantment Arctic Breath Duration 2",
  "Enchantment Arctic Breath Area Of Effect 1",
  "Enchantment Arctic Breath Area Of Effect 2",
  "Enchantment Armageddon Brand Damage 1",
  "Enchantment Armageddon Brand Damage 2",
  "Enchantment Assassins Mark Curse Effect 1",
  "Enchantment Assassins Mark Curse Effect 2",
  "Enchantment Assassins Mark Duration 1",
  "Enchantment Assassins Mark Duration 2",
  "Enchantment Ball Lightning Additional Projectiles 1",
  "Enchantment Ball Lightning Damage 1",
  "Enchantment Ball Lightning Damage 2",
  "Enchantment Ball Lightning Area Of Effect 1",
  "Enchantment Ball Lightning Area Of Effect 2",
  "Enchantment Bane Area Of Effect 1",
  "Enchantment Bane Area Of Effect 2",
  "Enchantment Bane Damage 1",
  "Enchantment Bane Damage 2",
  "Enchantment Bane Linked Curse Effect 1",
  "Enchantment Bane Linked Curse Effect 2",
  "Enchantment Barrage Attack Speed 1",
  "Enchantment Barrage Attack Speed 2",
  "Enchantment Barrage Damage 1",
  "Enchantment Barrage Damage 2",
  "Enchantment Barrage Num Of Additional Projectiles 1",
  "Enchantment Bear Trap Cooldown Speed 1",
  "Enchantment Bear Trap Cooldown Speed 2",
  "Enchantment Bear Trap Damage 1",
  "Enchantment Bear Trap Damage 2",
  "Enchantment Bear Trap Damage Taken 1",
  "Enchantment Bear Trap Damage Taken 2",
  "Enchantment Bladefall Additional Volley",
  "Enchantment Bladefall Critical Strike Chance 1",
  "Enchantment Bladefall Critical Strike Chance 2",
  "Enchantment Bladefall Damage 1",
  "Enchantment Bladefall Damage 2",
  "Enchantment Bladefall Area Of Effect 1",
  "Enchantment Bladefall Area Of Effect 2",
  "Enchantment Blade Vortex Crit Multi Per Blade 1",
  "Enchantment Blade Vortex Crit Multi Per Blade 2",
  "Enchantment Blade Vortex Damage 1",
  "Enchantment Blade Vortex Damage 2",
  "Enchantment Blade Vortex Duration 1",
  "Enchantment Blade Vortex Duration 2",
  "Enchantment Blade Vortex Area Of Effect 1",
  "Enchantment Blade Vortex Area Of Effect 2",
  "Enchantment Blast Rain Additional Blast 1",
  "Enchantment Blast Rain Additional Blast 2",
  "Enchantment Blast Rain Damage 1",
  "Enchantment Blast Rain Damage 2",
  "Enchantment Blast Rain Area Of Effect 1",
  "Enchantment Blast Rain Area Of Effect 2",
  "Enchantment Blight Damage 1",
  "Enchantment Blight Damage 2",
  "Enchantment Blight Area Of Effect 1",
  "Enchantment Blight Area Of Effect 2",
  "Enchantment Blight Secondary Skill Duration 1",
  "Enchantment Blight Secondary Skill Duration 2",
  "Enchantment Blink Arrow Attack Speed 1",
  "Enchantment Blink Arrow Attack Speed 2",
  "Enchantment Blink Arrow Cooldown Speed 1",
  "Enchantment Blink Arrow Cooldown Speed 2",
  "Enchantment Blink Arrow Damage 1",
  "Enchantment Blink Arrow Damage 2",
  "Enchantment Blood Rage Attack Speed 1",
  "Enchantment Blood Rage Attack Speed 2",
  "Enchantment Blood Rage Frenzy On Kill 1",
  "Enchantment Blood Rage Frenzy On Kill 2",
  "Enchantment Body Swap Cast Speed 1",
  "Enchantment Body Swap Cast Speed 2",
  "Enchantment Body Swap Damage 1",
  "Enchantment Body Swap Damage 2",
  "Enchantment Unearth Cast Speed 1",
  "Enchantment Unearth Cast Speed 2",
  "Enchantment Unearth Corpse Level 1",
  "Enchantment Unearth Corpse Level 2",
  "Enchantment Unearth Damage 1",
  "Enchantment Unearth Damage 2",
  "Enchantment Bone Offering Block Chance 1",
  "Enchantment Bone Offering Block Chance 2",
  "Enchantment Bone Offering Duration 1",
  "Enchantment Bone Offering Duration 2",
  "Enchantment Burning Arrow Damage 1",
  "Enchantment Burning Arrow Damage 2",
  "Enchantment Burning Arrow Ignite Chance 1",
  "Enchantment Burning Arrow Ignite Chance 2",
  "Enchantment Burning Arrow Physical Damage Percent To Add As Fire Damage 1",
  "Enchantment Burning Arrow Physical Damage Percent To Add As Fire Damage 2",
  "Enchantment Caustic Arrow Damage 1",
  "Enchantment Caustic Arrow Damage 2",
  "Enchantment Caustic Arrow Duration 1",
  "Enchantment Caustic Arrow Duration 2",
  "Enchantment Caustic Arrow Area Of Effect 1",
  "Enchantment Caustic Arrow Area Of Effect 2",
  "Enchantment Caustic Arrow Wither On Hit 1",
  "Enchantment Caustic Arrow Wither On Hit 2",
  "Enchantment Chaos Golem Elemental Resistances 1",
  "Enchantment Chaos Golem Elemental Resistances 2",
  "Enchantment Chaos Golem Percent Additional Physical Damage Reduction 1",
  "Enchantment Chaos Golem Percent Additional Physical Damage Reduction 2",
  "Enchantment Blade Flurry Damage 1",
  "Enchantment Blade Flurry Damage 2",
  "Enchantment Blade Flurry Dodge Per Stack 1",
  "Enchantment Blade Flurry Dodge Per Stack 2",
  "Enchantment Blade Flurry Area Of Effect 1",
  "Enchantment Blade Flurry Area Of Effect 2",
  "Enchantment Charged Dash Damage 1",
  "Enchantment Charged Dash Damage 2",
  "Enchantment Charged Dash Dodge When Finished Channelling 1",
  "Enchantment Charged Dash Dodge When Finished Channelling 2",
  "Enchantment Charged Dash Movement Speed 1",
  "Enchantment Charged Dash Movement Speed 2",
  "Enchantment Charged Dash Radius Final Explosion 1",
  "Enchantment Charged Dash Radius Final Explosion 2",
  "Enchantment Clarity Mana Reservation 1",
  "Enchantment Clarity Mana Reservation 2",
  "Enchantment Cleave Attack Speed 1",
  "Enchantment Cleave Attack Speed 2",
  "Enchantment Cleave Damage 1",
  "Enchantment Cleave Damage 2",
  "Enchantment Cleave Area Of Effect 1",
  "Enchantment Cleave Area Of Effect 2",
  "Enchantment Cold Snap Cooldown Speed 1",
  "Enchantment Cold Snap Cooldown Speed 2",
  "Enchantment Cold Snap Damage 1",
  "Enchantment Cold Snap Damage 2",
  "Enchantment Cold Snap Area Of Effect 1",
  "Enchantment Cold Snap Area Of Effect 2",
  "Enchantment Conductivity Curse Effect 1",
  "Enchantment Conductivity Curse Effect 2",
  "Enchantment Conductivity Duration 1",
  "Enchantment Conductivity Duration 2",
  "Enchantment Consecrated Path Damage 1",
  "Enchantment Consecrated Path Damage 2",
  "Enchantment Consecrated Path Area Of Effect 1",
  "Enchantment Consecrated Path Area Of Effect 2",
  "Enchantment Consecrated Path Range 1",
  "Enchantment Consecrated Path Range 2",
  "Enchantment Contagion Damage 1",
  "Enchantment Contagion Damage 2",
  "Enchantment Contagion Duration 1",
  "Enchantment Contagion Duration 2",
  "Enchantment Contagion Radius 1",
  "Enchantment Contagion Radius 2",
  "Enchantment Conversion Trap Cooldown Speed 1",
  "Enchantment Conversion Trap Cooldown Speed 2",
  "Enchantment Conversion Trap Damage 1",
  "Enchantment Conversion Trap Damage 2",
  "Enchantment Convocation Cooldown Speed 1",
  "Enchantment Convocation Cooldown Speed 2",
  "Enchantment Convocation Life Regeneration 1",
  "Enchantment Convocation Life Regeneration 2",
  "Enchantment Cremation Cast Speed 1",
  "Enchantment Cremation Cast Speed 2",
  "Enchantment Cremation Damage 1",
  "Enchantment Cremation Damage 2",
  "Enchantment Cremation Maximum Geysers 1",
  "Enchantment Cyclone Attack Speed 1",
  "Enchantment Cyclone Attack Speed 2",
  "Enchantment Cyclone Damage 1",
  "Enchantment Cyclone Damage 2",
  "Enchantment Decoy Totem Life 1",
  "Enchantment Decoy Totem Life 2",
  "Enchantment Decoy Totem Area Of Effect 1",
  "Enchantment Decoy Totem Area Of Effect 2",
  "Enchantment Desecrate Additional Corpse 1",
  "Enchantment Desecrate Additional Corpse 2",
  "Enchantment Desecrate Cooldown Speed 1",
  "Enchantment Desecrate Cooldown Speed 2",
  "Enchantment Despair Duration 1",
  "Enchantment Despair Duration 2",
  "Enchantment Despair Effect 1",
  "Enchantment Despair Effect 2",
  "Enchantment Determination Mana Reservation 1",
  "Enchantment Determination Mana Reservation 2",
  "Enchantment Detonate Dead Damage 1",
  "Enchantment Detonate Dead Damage 2",
  "Enchantment Detonate Dead Percent Chance To Detonate Additional Corpse 1",
  "Enchantment Detonate Dead Percent Chance To Detonate Additional Corpse 2",
  "Enchantment Detonate Dead Area Of Effect 1",
  "Enchantment Detonate Dead Area Of Effect 2",
  "Enchantment Devouring Totem Leech Per Second 1",
  "Enchantment Devouring Totem Leech Per Second 2",
  "Enchantment Devouring Totem Percent Chance To Consume Additional Corpse 1",
  "Enchantment Devouring Totem Percent Chance To Consume Additional Corpse 2",
  "Enchantment Discharge Consume Charges 1",
  "Enchantment Discharge Consume Charges 2",
  "Enchantment Discharge Damage 1",
  "Enchantment Discharge Damage 2",
  "Enchantment Discharge Area of Effect 1",
  "Enchantment Discharge Area of Effect 2",
  "Enchantment Discipline Mana Reservation 1",
  "Enchantment Discipline Mana Reservation 2",
  "Enchantment Divine Ire Beam Width 1",
  "Enchantment Divine Ire Beam Width 2",
  "Enchantment Divine Ire Damage 1",
  "Enchantment Divine Ire Damage 2",
  "Enchantment Divine Ire Number Of Additional Nearby Enemies To Zap 1",
  "Enchantment Divine Ire Number Of Additional Nearby Enemies To Zap 2",
  "Enchantment Dominating Blow Additional Magic 1",
  "Enchantment Dominating Blow Additional Magic 2",
  "Enchantment Dominating Blow Additional Rare 1",
  "Enchantment Dominating Blow Duration 1",
  "Enchantment Dominating Blow Duration 2",
  "Enchantment Double Slash Added Phys To Bleeding 1",
  "Enchantment Double Slash Added Phys To Bleeding 2",
  "Enchantment Double Slash Critical Strikes 1",
  "Enchantment Double Slash Critical Strikes 2",
  "Enchantment Lacerate Damage 1",
  "Enchantment Lacerate Damage 2",
  "Enchantment Double Slash Area Of Effect 1",
  "Enchantment Double Slash Area Of Effect 2",
  "Enchantment Double Strike Attack Speed 1",
  "Enchantment Double Strike Attack Speed 2",
  "Enchantment Double Strike Critical Strike Chance 1",
  "Enchantment Double Strike Critical Strike Chance 2",
  "Enchantment Double Strike Damage 1",
  "Enchantment Double Strike Damage 2",
  "Enchantment Double Strike Double Damage Vs Bleeding 1",
  "Enchantment Double Strike Double Damage Vs Bleeding 2",
  "Enchantment Dread Banner Effect 1",
  "Enchantment Dread Banner Effect 2",
  "Enchantment Dual Strike Attack Speed 1",
  "Enchantment Dual Strike Attack Speed 2",
  "Enchantment Dual Strike Critical Strike Chance 1",
  "Enchantment Dual Strike Critical Strike Chance 2",
  "Enchantment Dual Strike Damage 1",
  "Enchantment Dual Strike Damage 2",
  "Enchantment Earthquake Damage 1",
  "Enchantment Earthquake Damage 2",
  "Enchantment Earthquake Duration 1",
  "Enchantment Earthquake Duration 2",
  "Enchantment Earthquake Area Of Effect 1",
  "Enchantment Earthquake Area Of Effect 2",
  "Enchantment Elemental Hit Attack Speed 1",
  "Enchantment Elemental Hit Attack Speed 2",
  "Enchantment Elemental Hit Chance To Freeze Shock Ignite 1",
  "Enchantment Elemental Hit Chance To Freeze Shock Ignite 2",
  "Enchantment Elemental Hit Damage 1",
  "Enchantment Elemental Hit Damage 2",
  "Enchantment Elemental Weakness Curse Effect 1",
  "Enchantment Elemental Weakness Curse Effect 2",
  "Enchantment Elemental Weakness Duration 1",
  "Enchantment Elemental Weakness Duration 2",
  "Enchantment Enduring Cry Cooldown Speed 1",
  "Enchantment Enduring Cry Cooldown Speed 2",
  "Enchantment Enduring Cry Life Regeneration 1",
  "Enchantment Enduring Cry Life Regeneration 2",
  "Enchantment Enfeeble Curse Effect 1",
  "Enchantment Enfeeble Curse Effect 2",
  "Enchantment Enfeeble Duration 1",
  "Enchantment Enfeeble Duration 2",
  "Enchantment Essence Drain Damage 1",
  "Enchantment Essence Drain Damage 2",
  "Enchantment Essence Drain Duration 1",
  "Enchantment Essence Drain Duration 2",
  "Enchantment Ethereal Knives Damage 1",
  "Enchantment Ethereal Knives Damage 2",
  "Enchantment Ethereal Knives Number Of Targets To Pierce 1",
  "Enchantment Ethereal Knives Projectile Speed 1",
  "Enchantment Ethereal Knives Projectile Speed 2",
  "Enchantment Explosive Arrow Attack Speed 1",
  "Enchantment Explosive Arrow Attack Speed 2",
  "Enchantment Explosive Arrow Damage 1",
  "Enchantment Explosive Arrow Damage 2",
  "Enchantment Explosive Arrow Area Of Effect 1",
  "Enchantment Explosive Arrow Area Of Effect 2",
  "Enchantment Fireball Cast Speed 1",
  "Enchantment Fireball Cast Speed 2",
  "Enchantment Fireball Damage 1",
  "Enchantment Fireball Damage 2",
  "Enchantment Fireball Ignite Chance 1",
  "Enchantment Fireball Ignite Chance 2",
  "Enchantment Fire Beam Cast Speed 1",
  "Enchantment Fire Beam Cast Speed 2",
  "Enchantment Scorching Ray Damage 1",
  "Enchantment Scorching Ray Damage 2",
  "Enchantment Fire Beam Length 1",
  "Enchantment Fire Beam Length 2",
  "Enchantment Fire Nova Mine Cast Speed 1",
  "Enchantment Fire Nova Mine Cast Speed 2",
  "Enchantment Fire Nova Mine Damage 1",
  "Enchantment Fire Nova Mine Damage 2",
  "Enchantment Fire Nova Mine Num Of Additional Repeats 1",
  "Enchantment Fire Nova Mine Num Of Additional Repeats 2",
  "Enchantment Firestorm Damage 1",
  "Enchantment Firestorm Damage 2",
  "Enchantment Firestorm Duration 1",
  "Enchantment Firestorm Duration 2",
  "Enchantment Firestorm Explosion Area Of Effect 1",
  "Enchantment Firestorm Explosion Area Of Effect 2",
  "Enchantment Fire Trap Burning Damage 1",
  "Enchantment Fire Trap Burning Damage 2",
  "Enchantment Fire Trap Burning Ground Duration 1",
  "Enchantment Fire Trap Burning Ground Duration 2",
  "Enchantment Fire Trap Damage 1",
  "Enchantment Fire Trap Damage 2",
  "Enchantment Flameblast Critical Strike Chance 1",
  "Enchantment Flameblast Critical Strike Chance 2",
  "Enchantment Flameblast Damage 1",
  "Enchantment Flameblast Damage 2",
  "Enchantment Flameblast Area Of Effect 1",
  "Enchantment Flameblast Area Of Effect 2",
  "Enchantment Flame Dash Cooldown Speed 1",
  "Enchantment Flame Dash Cooldown Speed 2",
  "Enchantment Flame Dash Damage 1",
  "Enchantment Flame Dash Damage 2",
  "Enchantment Flame Golem Elemental Resistances 1",
  "Enchantment Flame Golem Elemental Resistances 2",
  "Enchantment Flame Golem Granted Buff Effect 1",
  "Enchantment Flame Golem Granted Buff Effect 2",
  "Enchantment Flame Surge Critical Strike Chance 1",
  "Enchantment Flame Surge Critical Strike Chance 2",
  "Enchantment Flame Surge Damage 1",
  "Enchantment Flame Surge Damage 2",
  "Enchantment Flame Surge Vs Burning Enemies 1",
  "Enchantment Flame Surge Vs Burning Enemies 2",
  "Enchantment Flamethrower Additional Flamethrowers 1",
  "Enchantment Flamethrower Additional Flamethrowers 2",
  "Enchantment Flamethrower Trap Cast Speed 1",
  "Enchantment Flamethrower Trap Cast Speed 2",
  "Enchantment Flamethrower Trap Cooldown Speed 1",
  "Enchantment Flamethrower Trap Cooldown Speed 2",
  "Enchantment Flamethrower Trap Damage 1",
  "Enchantment Flamethrower Trap Damage 2",
  "Enchantment Flamethrower Trap Duration 1",
  "Enchantment Flamethrower Trap Duration 2",
  "Enchantment Flame Totem Consecrated Ground Enemy Damage Taken 1",
  "Enchantment Flame Totem Consecrated Ground Enemy Damage Taken 2",
  "Enchantment Flame Totem Damage 1",
  "Enchantment Flame Totem Damage 2",
  "Enchantment Flame Totem Num Of Additional Projectiles 1",
  "Enchantment Flame Totem Num Of Additional Projectiles 2",
  "Enchantment Flame Totem Projectile Speed 1",
  "Enchantment Flame Totem Projectile Speed 2",
  "Enchantment Flammability Curse Effect 1",
  "Enchantment Flammability Curse Effect 2",
  "Enchantment Flammability Duration 1",
  "Enchantment Flammability Duration 2",
  "Enchantment Flesh Offering Attack Speed 1",
  "Enchantment Flesh Offering Attack Speed 2",
  "Enchantment Flesh Offering Duration 1",
  "Enchantment Flesh Offering Duration 2",
  "Enchantment Flicker Strike Cooldown Speed 1",
  "Enchantment Flicker Strike Cooldown Speed 2",
  "Enchantment Flicker Strike Damage 1",
  "Enchantment Flicker Strike Damage 2",
  "Enchantment Flicker Strike Damage Per Frenzy Charge 1",
  "Enchantment Flicker Strike Damage Per Frenzy Charge 2",
  "Enchantment Freeze Mine Cold Penetration 1",
  "Enchantment Freeze Mine Cold Penetration 2",
  "Enchantment Freeze Mine Area Of Effect 1",
  "Enchantment Freeze Mine Area Of Effect 2",
  "Enchantment Freezing Pulse Cast Speed 1",
  "Enchantment Freezing Pulse Cast Speed 2",
  "Enchantment Freezing Pulse Damage 1",
  "Enchantment Freezing Pulse Damage 2",
  "Enchantment Freezing Pulse Projectile Speed 1",
  "Enchantment Freezing Pulse Projectile Speed 2",
  "Enchantment Frenzy Damage 1",
  "Enchantment Frenzy Damage 2",
  "Enchantment Frenzy Damage Per Frenzy Charge 1",
  "Enchantment Frenzy Damage Per Frenzy Charge 2",
  "Enchantment Frenzy Percent Chance To Gain Additional Frenzy Charge 1",
  "Enchantment Frenzy Percent Chance To Gain Additional Frenzy Charge 2",
  "Enchantment Frostbite Curse Effect 1",
  "Enchantment Frostbite Curse Effect 2",
  "Enchantment Frostbite Duration 1",
  "Enchantment Frostbite Duration 2",
  "Enchantment Frost Blades Damage 1",
  "Enchantment Frost Blades Damage 2",
  "Enchantment Frost Blades Projectile Speed 1",
  "Enchantment Frost Blades Projectile Speed 2",
  "Enchantment Frost Bolt Cast Speed 1",
  "Enchantment Frost Bolt Cast Speed 2",
  "Enchantment Frost Bolt Damage 1",
  "Enchantment Frost Bolt Damage 2",
  "Enchantment Frost Bolt Freeze Chance 1",
  "Enchantment Frost Bolt Freeze Chance 2",
  "Enchantment Frost Bomb Cooldown Speed 1",
  "Enchantment Frost Bomb Cooldown Speed 2",
  "Enchantment Frost Bomb Damage 1",
  "Enchantment Frost Bomb Damage 2",
  "Enchantment Frost Bomb Increased Duration 1",
  "Enchantment Frost Bomb Increased Duration 2",
  "Enchantment Frost Bomb Area Of Effect 1",
  "Enchantment Frost Bomb Area Of Effect 2",
  "Enchantment Frost Fury Additional Max Number Of Stages 1",
  "Enchantment Frost Fury Area Of Effect Per Stage 1",
  "Enchantment Frost Fury Area Of Effect Per Stage 2",
  "Enchantment Frost Wall Cooldown Speed 1",
  "Enchantment Frost Wall Cooldown Speed 2",
  "Enchantment Frost Wall Duration 1",
  "Enchantment Frost Wall Duration 2",
  "Enchantment Glacial Cascade Damage 1",
  "Enchantment Glacial Cascade Damage 2",
  "Enchantment Glacial Cascade Physical Damage Percent To Convert To Cold 1",
  "Enchantment Glacial Cascade Physical Damage Percent To Convert To Cold 2",
  "Enchantment Glacial Cascade Area Of Effect 1",
  "Enchantment Glacial Cascade Area Of Effect 2",
  "Enchantment Glacial Hammer Damage 1",
  "Enchantment Glacial Hammer Damage 2",
  "Enchantment Glacial Hammer Freeze Chance 1",
  "Enchantment Glacial Hammer Freeze Chance 2",
  "Enchantment Glacial Hammer Physical Damage Percent To Add As Cold Damage 1",
  "Enchantment Glacial Hammer Physical Damage Percent To Add As Cold Damage 2",
  "Enchantment Grace Mana Reservation 1",
  "Enchantment Grace Mana Reservation 2",
  "Enchantment Ground Slam Angle 1",
  "Enchantment Ground Slam Angle 2",
  "Enchantment Ground Slam Damage 1",
  "Enchantment Ground Slam Damage 2",
  "Enchantment Ground Slam Area Of Effect 1",
  "Enchantment Ground Slam Area Of Effect 2",
  "Enchantment Haste Mana Reservation 1",
  "Enchantment Haste Mana Reservation 2",
  "Enchantment Hatred Mana Reservation 1",
  "Enchantment Hatred Mana Reservation 2",
  "Enchantment Heavy Strike Attack Speed 1",
  "Enchantment Heavy Strike Attack Speed 2",
  "Enchantment Heavy Strike Damage 1",
  "Enchantment Heavy Strike Damage 2",
  "Enchantment Heavy Strike Double Damage 1",
  "Enchantment Heavy Strike Double Damage 2",
  "Enchantment Herald Of Agony Mana Reservation 1",
  "Enchantment Herald Of Agony Mana Reservation 2",
  "Enchantment Herald Of Agony Num Of Secondary Projectiles 1",
  "Enchantment Herald Of Ash Damage 1",
  "Enchantment Herald Of Ash Damage 2",
  "Enchantment Herald Of Ash Mana Reservation 1",
  "Enchantment Herald Of Ash Mana Reservation 2",
  "Enchantment Herald Of Ice Damage 1",
  "Enchantment Herald Of Ice Damage 2",
  "Enchantment Herald Of Ice Mana Reservation 1",
  "Enchantment Herald Of Ice Mana Reservation 2",
  "Enchantment Herald Of Purity Additional Minion 1",
  "Enchantment Herald Of Purity Mana Reservation 1",
  "Enchantment Herald Of Purity Mana Reservation 2",
  "Enchantment Herald Of Thunder Damage 1",
  "Enchantment Herald Of Thunder Damage 2",
  "Enchantment Herald Of Thunder Mana Reservation 1",
  "Enchantment Herald Of Thunder Mana Reservation 2",
  "Enchantment Holy Relic Buff Effect 1",
  "Enchantment Holy Relic Buff Effect 2",
  "Enchantment Holy Relic Damage 1",
  "Enchantment Holy Relic Damage 2",
  "Enchantment Holy Relic Area Of Effect 1",
  "Enchantment Holy Relic Area Of Effect 2",
  "Enchantment Ice Crash Damage 1",
  "Enchantment Ice Crash Damage 2",
  "Enchantment Ice Crash Physical Damage Percent To Add As Cold Damage 1",
  "Enchantment Ice Crash Physical Damage Percent To Add As Cold Damage 2",
  "Enchantment Ice Crash Area Of Effect 1",
  "Enchantment Ice Crash Area Of Effect 2",
  "Enchantment Ice Golem Elemental Resistances 1",
  "Enchantment Ice Golem Elemental Resistances 2",
  "Enchantment Ice Golem Grants Percent Additional Critical Strike Chance And Accuracy 1",
  "Enchantment Ice Golem Grants Percent Additional Critical Strike Chance And Accuracy 2",
  "Enchantment Ice Nova Damage 1",
  "Enchantment Ice Nova Damage 2",
  "Enchantment Ice Nova Freeze Chance 1",
  "Enchantment Ice Nova Freeze Chance 2",
  "Enchantment Ice Nova Minimum Chill 1",
  "Enchantment Ice Nova Minimum Chill 2",
  "Enchantment Ice Nova Area Of Effect 1",
  "Enchantment Ice Nova Area Of Effect 2",
  "Enchantment Ice Shot Damage 1",
  "Enchantment Ice Shot Damage 2",
  "Enchantment Ice Shot Duration 1",
  "Enchantment Ice Shot Duration 2",
  "Enchantment Ice Shot Area Of Effect 1",
  "Enchantment Ice Shot Area Of Effect 2",
  "Enchantment Ice Siphon Trap Chill Effect 1",
  "Enchantment Ice Siphon Trap Chill Effect 2",
  "Enchantment Ice Siphon Trap Damage 1",
  "Enchantment Ice Siphon Trap Damage 2",
  "Enchantment Ice Siphon Trap Damage Taken 1",
  "Enchantment Ice Siphon Trap Duration 1",
  "Enchantment Ice Siphon Trap Duration 2",
  "Enchantment Ice Spear Additional Projectile 1",
  "Enchantment Ice Spear Distance Before Form Change 1",
  "Enchantment Ice Spear Distance Before Form Change 2",
  "Enchantment Ice Spear Percent Chance To Gain Power Charge On Critical Strike 1",
  "Enchantment Ice Spear Percent Chance To Gain Power Charge On Critical Strike 2",
  "Enchantment Ice Spear Second Form Critical Strike Chance 1",
  "Enchantment Ice Spear Second Form Critical Strike Chance 2",
  "Enchantment Ice Trap Cold Penetration 1",
  "Enchantment Ice Trap Cold Penetration 2",
  "Enchantment Ice Trap Damage 1",
  "Enchantment Ice Trap Damage 2",
  "Enchantment Ice Trap Area Of Effect 1",
  "Enchantment Ice Trap Area Of Effect 2",
  "Enchantment Immortal Call Duration 1",
  "Enchantment Immortal Call Duration 2",
  "Enchantment Incinerate Area Of Effect 1",
  "Enchantment Incinerate Area Of Effect 2",
  "Enchantment Incinerate Damage 1",
  "Enchantment Incinerate Damage 2",
  "Enchantment Incinerate Damage Per Stage 3",
  "Enchantment Incinerate Maximum Stages 1",
  "Enchantment Incinerate Maximum Stages 2",
  "Enchantment Infernal Blow Damage 1",
  "Enchantment Infernal Blow Damage 2",
  "Enchantment Infernal Blow Increased Damage Per Stack 1",
  "Enchantment Infernal Blow Increased Damage Per Stack 2",
  "Enchantment Infernal Blow Physical Damage Percent To Add As Fire Damage 1",
  "Enchantment Infernal Blow Physical Damage Percent To Add As Fire Damage 2",
  "Enchantment Infernal Blow Area Of Effect 1",
  "Enchantment Infernal Blow Area Of Effect 2",
  "Enchantment Kinetic Blast Damage 1",
  "Enchantment Kinetic Blast Damage 2",
  "Enchantment Kinetic Blast Explosions 1",
  "Enchantment Kinetic Blast Explosions 2",
  "Enchantment Kinetic Blast Area Of Effect 1",
  "Enchantment Kinetic Blast Area Of Effect 2",
  "Enchantment Lancing Steel Damage 1",
  "Enchantment Lancing Steel Damage 2",
  "Enchantment Lancing Steel Impale Chance 1",
  "Enchantment Lancing Steel Impale Chance 2",
  "Enchantment Lancing Steel Primary Proj Pierce Num 1",
  "Enchantment Lancing Steel Primary Proj Pierce Num 2",
  "Enchantment Leap Slam Attack Speed 1",
  "Enchantment Leap Slam Attack Speed 2",
  "Enchantment Leap Slam Damage 1",
  "Enchantment Leap Slam Damage 2",
  "Enchantment Leap Slam Area Of Effect 1",
  "Enchantment Leap Slam Area Of Effect 2",
  "Enchantment Lightning Arrow Damage 1",
  "Enchantment Lightning Arrow Damage 2",
  "Enchantment Lightning Arrow Extra Targets 1",
  "Enchantment Lightning Arrow Extra Targets 2",
  "Enchantment Lightning Arrow Area Of Effect 1",
  "Enchantment Lightning Arrow Area Of Effect 2",
  "Enchantment Lightning Golem Elemental Resistances 1",
  "Enchantment Lightning Golem Elemental Resistances 2",
  "Enchantment Lightning Golem Granted Buff Effect 1",
  "Enchantment Lightning Golem Granted Buff Effect 2",
  "Enchantment Lightning Strike Additional Pierce 1",
  "Enchantment Lightning Strike Additional Pierce 2",
  "Enchantment Lightning Strike Damage 1",
  "Enchantment Lightning Strike Damage 2",
  "Enchantment Lightning Strike Num Of Additional Projectiles 1",
  "Enchantment Lightning Strike Num Of Additional Projectiles 2",
  "Enchantment Lightning Tendrils Critical Strike Chance 1",
  "Enchantment Lightning Tendrils Critical Strike Chance 2",
  "Enchantment Lightning Tendrils Damage 1",
  "Enchantment Lightning Tendrils Damage 2",
  "Enchantment Lightning Tendrils Area Of Effect 1",
  "Enchantment Lightning Tendrils Area Of Effect 2",
  "Enchantment Lightning Tower Trap Additional Beams 1",
  "Enchantment Lightning Tower Trap Cast Speed 1",
  "Enchantment Lightning Tower Trap Cast Speed 2",
  "Enchantment Lightning Tower Trap Cooldown Speed 1",
  "Enchantment Lightning Tower Trap Cooldown Speed 2",
  "Enchantment Lightning Tower Trap Damage 1",
  "Enchantment Lightning Tower Trap Damage 2",
  "Enchantment Lightning Tower Trap Duration 1",
  "Enchantment Lightning Tower Trap Duration 2",
  "Enchantment Lightning Trap Additional Pierce 1",
  "Enchantment Lightning Trap Additional Pierce 2",
  "Enchantment Lightning Trap Damage 1",
  "Enchantment Lightning Trap Damage 2",
  "Enchantment Lightning Trap Penetration 1",
  "Enchantment Lightning Trap Penetration 2",
  "Enchantment Lightning Trap Shock Effect 1",
  "Enchantment Lightning Trap Shock Effect 2",
  "Enchantment Lightning Warp Cast Speed 1",
  "Enchantment Lightning Warp Cast Speed 2",
  "Enchantment Lightning Warp Damage 1",
  "Enchantment Lightning Warp Damage 2",
  "Enchantment Lightning Warp Duration 1",
  "Enchantment Lightning Warp Duration 2",
  "Enchantment Magma Orb Damage 1",
  "Enchantment Magma Orb Damage 2",
  "Enchantment Magma Orb Num Of Additional Projectiles In Chain 1",
  "Enchantment Magma Orb Num Of Additional Projectiles In Chain 2",
  "Enchantment Magma Orb Area Of Effect 1",
  "Enchantment Magma Orb Area Of Effect 2",
  "Enchantment Malevolence Mana Reservation 1",
  "Enchantment Malevolence Mana Reservation 2",
  "Enchantment Mirror Arrow Attack Speed 1",
  "Enchantment Mirror Arrow Attack Speed 2",
  "Enchantment Mirror Arrow Cooldown Speed 1",
  "Enchantment Mirror Arrow Cooldown Speed 2",
  "Enchantment Mirror Arrow Damage 1",
  "Enchantment Mirror Arrow Damage 2",
  "Enchantment Molten Shell Armour 1",
  "Enchantment Molten Shell Armour 2",
  "Enchantment Molten Shell Duration 1",
  "Enchantment Molten Shell Duration 2",
  "Enchantment Molten Strike Damage 1",
  "Enchantment Molten Strike Damage 2",
  "Enchantment Molten Strike Num Of Additional Projectiles 1",
  "Enchantment Molten Strike Num Of Additional Projectiles 2",
  "Enchantment Molten Strike Area Of Effect 1",
  "Enchantment Molten Strike Area Of Effect 2",
  "Enchantment Orb Of Storms Cast Speed 1",
  "Enchantment Orb Of Storms Cast Speed 2",
  "Enchantment Orb Of Storms Damage 1",
  "Enchantment Orb Of Storms Damage 2",
  "Enchantment Phase Run Duration 1",
  "Enchantment Phase Run Duration 2",
  "Enchantment Phase Run Percent Chance To Not Consume Frenzy Charges 1",
  "Enchantment Phase Run Percent Chance To Not Consume Frenzy Charges 2",
  "Enchantment Physical Cascade Additional Cascades 1",
  "Enchantment Physical Cascade Cooldown Speed 1",
  "Enchantment Physical Cascade Cooldown Speed 2",
  "Enchantment Physical Cascade Trap Damage 1",
  "Enchantment Physical Cascade Trap Damage 2",
  "Enchantment Physical Cascade Trap Duration 1",
  "Enchantment Physical Cascade Trap Duration 2",
  "Enchantment Poachers Mark Curse Effect 1",
  "Enchantment Poachers Mark Curse Effect 2",
  "Enchantment Poachers Mark Duration 1",
  "Enchantment Poachers Mark Duration 2",
  "Enchantment Power Siphon Additional Projectiles 1",
  "Enchantment Power Siphon Additional Projectiles 2",
  "Enchantment Power Siphon Attack Speed 1",
  "Enchantment Power Siphon Attack Speed 2",
  "Enchantment Power Siphon Damage 1",
  "Enchantment Power Siphon Damage 2",
  "Enchantment Power Siphon Percent Chance To Gain Power Charge On Kill 1",
  "Enchantment Power Siphon Percent Chance To Gain Power Charge On Kill 2",
  "Enchantment Precision Mana Reservation 1",
  "Enchantment Precision Mana Reservation 2",
  "Enchantment Projectile Weakness Curse Effect 1",
  "Enchantment Projectile Weakness Curse Effect 2",
  "Enchantment Projectile Weakness Duration 1",
  "Enchantment Projectile Weakness Duration 2",
  "Enchantment Puncture Damage 1",
  "Enchantment Puncture Damage 2",
  "Enchantment Puncture Duration 1",
  "Enchantment Puncture Duration 2",
  "Enchantment Puncture Maim On Hit Percent Chance 1",
  "Enchantment Puncture Maim On Hit Percent Chance 2",
  "Enchantment Punishment Curse Effect 1",
  "Enchantment Punishment Curse Effect 2",
  "Enchantment Punishment Duration 1",
  "Enchantment Punishment Duration 2",
  "Enchantment Purifying Flame Area Of Effect When Targeting Consecrated Ground 1",
  "Enchantment Purifying Flame Area Of Effect When Targeting Consecrated Ground 2",
  "Enchantment Purifying Flame Consecrated Ground Enemy Damage Taken 1",
  "Enchantment Purifying Flame Consecrated Ground Enemy Damage Taken 2",
  "Enchantment Purifying Flame Damage 1",
  "Enchantment Purifying Flame Damage 2",
  "Enchantment Purity Of Elements Mana Reservation 1",
  "Enchantment Purity Of Elements Mana Reservation 2",
  "Enchantment Purity Of Fire Mana Reservation 1",
  "Enchantment Purity Of Fire Mana Reservation 2",
  "Enchantment Purity Of Ice Mana Reservation 1",
  "Enchantment Purity Of Ice Mana Reservation 2",
  "Enchantment Purity Of Lightning Mana Reservation 1",
  "Enchantment Purity Of Lightning Mana Reservation 2",
  "Enchantment Rain Of Arrows Attack Speed 1",
  "Enchantment Rain Of Arrows Attack Speed 2",
  "Enchantment Rain Of Arrows Damage 1",
  "Enchantment Rain Of Arrows Damage 2",
  "Enchantment Rain Of Arrows Area Of Effect 1",
  "Enchantment Rain Of Arrows Area Of Effect 2",
  "Enchantment Rain Of Arrows Repeat Count 1",
  "Enchantment Rain Of Arrows Repeat Count 2",
  "Enchantment Raise Spectre Damage 1",
  "Enchantment Raise Spectre Damage 2",
  "Enchantment Raise Zombie Damage 1",
  "Enchantment Raise Zombie Damage 2",
  "Enchantment Rallying Cry Buff Effect 1",
  "Enchantment Rallying Cry Buff Effect 2",
  "Enchantment Rallying Cry Duration 1",
  "Enchantment Rallying Cry Duration 2",
  "Enchantment Reave Damage 1",
  "Enchantment Reave Damage 2",
  "Enchantment Reave Area Of Effect 1",
  "Enchantment Reave Area Of Effect 2",
  "Enchantment Reckoning Cooldown Speed 1",
  "Enchantment Reckoning Cooldown Speed 2",
  "Enchantment Reckoning Damage 1",
  "Enchantment Reckoning Damage 2",
  "Enchantment Rejuvination Totem Life Regeneration 1",
  "Enchantment Rejuvination Totem Life Regeneration 2",
  "Enchantment Rejuvination Totem Percent Life Regeneration Added As Mana Regeneration 1",
  "Enchantment Rejuvination Totem Percent Life Regeneration Added As Mana Regeneration 2",
  "Enchantment Righteous Fire Damage 1",
  "Enchantment Righteous Fire Damage 2",
  "Enchantment Righteous Fire Area Of Effect 1",
  "Enchantment Righteous Fire Area Of Effect 2",
  "Enchantment Righteous Fire Spell Damage 1",
  "Enchantment Righteous Fire Spell Damage 2",
  "Enchantment Riposte Cooldown Speed 1",
  "Enchantment Riposte Cooldown Speed 2",
  "Enchantment Riposte Damage 1",
  "Enchantment Riposte Damage 2",
  "Enchantment Scourge Arrow Additional Spore 1",
  "Enchantment Scourge Arrow Chance To Poison 1",
  "Enchantment Scourge Arrow Chance To Poison 2",
  "Enchantment Scourge Arrow Damage 1",
  "Enchantment Scourge Arrow Damage 2",
  "Enchantment Searing Bond Damage 1",
  "Enchantment Searing Bond Damage 2",
  "Enchantment Searing Bond Totem Elemental Resistances 1",
  "Enchantment Searing Bond Totem Elemental Resistances 2",
  "Enchantment Searing Bond Totem Placement Speed 1",
  "Enchantment Searing Bond Totem Placement Speed 2",
  "Enchantment Shattering Steel Additional Projectile 1",
  "Enchantment Shattering Steel Damage 1",
  "Enchantment Shattering Steel Damage 2",
  "Enchantment Shattering Steel Fortify On Hit Close Range 1",
  "Enchantment Shield Charge Attack Speed 1",
  "Enchantment Shield Charge Attack Speed 2",
  "Enchantment Shield Charge Damage 1",
  "Enchantment Shield Charge Damage 2",
  "Enchantment Shock Nova Damage 1",
  "Enchantment Shock Nova Damage 2",
  "Enchantment Shock Nova Larger Ring Damage 1",
  "Enchantment Shock Nova Larger Ring Damage 2",
  "Enchantment Shock Nova Area Of Effect 1",
  "Enchantment Shock Nova Area Of Effect 2",
  "Enchantment Shockwave Totem Cast Speed 1",
  "Enchantment Shockwave Totem Cast Speed 2",
  "Enchantment Shockwave Totem Damage 1",
  "Enchantment Shockwave Totem Damage 2",
  "Enchantment Shockwave Totem Radius 1",
  "Enchantment Shockwave Totem Radius 2",
  "Enchantment Shrapnel Shot Damage 1",
  "Enchantment Shrapnel Shot Damage 2",
  "Enchantment Shrapnel Shot Physical Damage Percent To Add As Lightning Damage 1",
  "Enchantment Shrapnel Shot Physical Damage Percent To Add As Lightning Damage 2",
  "Enchantment Shrapnel Shot Radius 1",
  "Enchantment Shrapnel Shot Radius 2",
  "Enchantment Shrapnel Trap Damage 1",
  "Enchantment Shrapnel Trap Damage 2",
  "Enchantment Shrapnel Trap Radius 1",
  "Enchantment Shrapnel Trap Radius 2",
  "Enchantment Shrapnel Trap Secondary Explosions 1",
  "Enchantment Shrapnel Trap Secondary Explosions 2",
  "Enchantment Siege Ballista Attack Speed 1",
  "Enchantment Siege Ballista Attack Speed 2",
  "Enchantment Siege Ballista Damage 1",
  "Enchantment Siege Ballista Damage 2",
  "Enchantment Siege Ballista Totem Placement Speed 1",
  "Enchantment Siege Ballista Totem Placement Speed 2",
  "Enchantment Dark Pact Area Of Effect 1",
  "Enchantment Dark Pact Area Of Effect 2",
  "Enchantment Dack Pact Cast Speed 1",
  "Enchantment Dack Pact Cast Speed 2",
  "Enchantment Dark Pact Damage 1",
  "Enchantment Dark Pact Damage 2",
  "Enchantment Smite Additional Target Chance 1",
  "Enchantment Smite Additional Target Chance 2",
  "Enchantment Smite Aura Effect 1",
  "Enchantment Smite Aura Effect 2",
  "Enchantment Smite Damage 1",
  "Enchantment Smite Damage 2",
  "Enchantment Smoke Mine Duration 1",
  "Enchantment Smoke Mine Duration 2",
  "Enchantment Smoke Mine Movement Speed 1",
  "Enchantment Smoke Mine Movement Speed 2",
  "Enchantment Soulrend Applies Hinder Movement Speed 1",
  "Enchantment Soulrend Applies Hinder Movement Speed 2",
  "Enchantment Soulrend Damage 1",
  "Enchantment Soulrend Damage 2",
  "Enchantment Soulrend Number Of Additional Projectiles 1",
  "Enchantment Spark Damage 1",
  "Enchantment Spark Damage 2",
  "Enchantment Spark Num Of Additional Projectiles 1",
  "Enchantment Spark Num Of Additional Projectiles 2",
  "Enchantment Spark Projectile Speed 1",
  "Enchantment Spark Projectile Speed 2",
  "Enchantment Spectral Shield Throw Damage 1",
  "Enchantment Spectral Shield Throw Damage 2",
  "Enchantment Spectral Shield Throw Num Of Additional Projectiles 1",
  "Enchantment Spectral Shield Throw Num Of Additional Projectiles 2",
  "Enchantment Spectral Shield Throw Projectile Speed 1",
  "Enchantment Spectral Shield Throw Projectile Speed 2",
  "Enchantment Spectral Throw Damage 1",
  "Enchantment Spectral Throw Damage 2",
  "Enchantment Spectral Throw Projectile Deceleration 1",
  "Enchantment Spectral Throw Projectile Deceleration 2",
  "Enchantment Spectral Throw Projectile Speed 1",
  "Enchantment Spectral Throw Projectile Speed 2",
  "Enchantment Spectre Attack And Cast Speed 1",
  "Enchantment Spectre Attack And Cast Speed 2",
  "Enchantment Spectre Elemental Resistances 1",
  "Enchantment Spectre Elemental Resistances 2",
  "Enchantment Spirit Offering Duration 1",
  "Enchantment Spirit Offering Duration 2",
  "Enchantment Spirit Offering Physical Added As Chaos 1",
  "Enchantment Spirit Offering Physical Added As Chaos 2",
  "Enchantment Split Arrow Critical Strike Chance 1",
  "Enchantment Split Arrow Critical Strike Chance 2",
  "Enchantment Split Arrow Damage 1",
  "Enchantment Split Arrow Damage 2",
  "Enchantment Split Arrow Num Of Additional Projectiles 1",
  "Enchantment Split Arrow Num Of Additional Projectiles 2",
  "Enchantment Static Strike Damage 1",
  "Enchantment Static Strike Damage 2",
  "Enchantment Static Strike Duration 1",
  "Enchantment Static Strike Duration 2",
  "Enchantment Static Strike Maximum Beam Targets 1",
  "Enchantment Static Strike Maximum Beam Targets 2",
  "Enchantment Static Strike Area Of Effect 1",
  "Enchantment Static Strike Area Of Effect 2",
  "Enchantment Stone Golem Elemental Resistances 1",
  "Enchantment Stone Golem Elemental Resistances 2",
  "Enchantment Stone Golem Granted Buff Effect 1",
  "Enchantment Stone Golem Granted Buff Effect 2",
  "Enchantment Storm Brand Damage 1",
  "Enchantment Storm Brand Damage 2",
  "Enchantment Storm Burst Additional Object Chance 1",
  "Enchantment Storm Burst Additional Object Chance 2",
  "Enchantment Storm Burst Damage 1",
  "Enchantment Storm Burst Damage 2",
  "Enchantment Storm Burst Area Of Effect 1",
  "Enchantment Storm Burst Area Of Effect 2",
  "Enchantment Storm Call Damage 1",
  "Enchantment Storm Call Damage 2",
  "Enchantment Storm Call Duration 1",
  "Enchantment Storm Call Duration 2",
  "Enchantment Storm Call Area Of Effect 1",
  "Enchantment Storm Call Area Of Effect 2",
  "Enchantment Orb of Storms Critical Strike Chance 1",
  "Enchantment Orb of Storms Critical Strike Chance 2",
  "Enchantment Orb of Storms Area Of Effect 1",
  "Enchantment Orb of Storms Area Of Effect 2",
  "Enchantment Summoned Raging Spirit Additional 1",
  "Enchantment Summoned Raging Spirit Additional 2",
  "Enchantment Summoned Raging Spirit Duration 1",
  "Enchantment Summoned Raging Spirit Duration 2",
  "Enchantment Summon Flame Golem Damage 1",
  "Enchantment Summon Flame Golem Damage 2",
  "Enchantment Summon Ice Golem Damage 1",
  "Enchantment Summon Ice Golem Damage 2",
  "Enchantment Summon Lightning Golem Damage 1",
  "Enchantment Summon Lightning Golem Damage 2",
  "Enchantment Summon Raging Spirit Damage 1",
  "Enchantment Summon Raging Spirit Damage 2",
  "Enchantment Summon Skeletons Damage 1",
  "Enchantment Summon Skeletons Damage 2",
  "Enchantment Summon Skeletons Additional Warrior Skeletons 1",
  "Enchantment Summon Skeletons Additional Warrior Skeletons 2",
  "Enchantment Summon Stone Golem Damage 1",
  "Enchantment Summon Stone Golem Damage 2",
  "Enchantment Sumon Chaos Golem Damage 1",
  "Enchantment Sumon Chaos Golem Damage 2",
  "Enchantment Sunder Attack Speed 1",
  "Enchantment Sunder Attack Speed 2",
  "Enchantment Sunder Damage 1",
  "Enchantment Sunder Damage 2",
  "Enchantment Sunder Radius 1",
  "Enchantment Sunder Radius 2",
  "Enchantment Sweep Damage 1",
  "Enchantment Sweep Damage 2",
  "Enchantment Sweep Knockback Chance 1",
  "Enchantment Sweep Knockback Chance 2",
  "Enchantment Sweep Area Of Effect 1",
  "Enchantment Sweep Area Of Effect 2",
  "Enchantment Tectonic Slam Area Of Effect 1",
  "Enchantment Tectonic Slam Area Of Effect 2",
  "Enchantment Tectonic Slam Chance To Charged Slam 1",
  "Enchantment Tectonic Slam Chance To Charged Slam 2",
  "Enchantment Tectonic Slam Damage 1",
  "Enchantment Tectonic Slam Damage 2",
  "Enchantment Tempest Shield Damage 1",
  "Enchantment Tempest Shield Damage 2",
  "Enchantment Tempest Shield Num Of Additional Projectiles In Chain 1",
  "Enchantment Tempest Shield Num Of Additional Projectiles In Chain 2",
  "Enchantment Temporal Chains Curse Effect 1",
  "Enchantment Temporal Chains Curse Effect 2",
  "Enchantment Temporal Chains Duration 1",
  "Enchantment Temporal Chains Duration 2",
  "Enchantment Tornado Shot Critical Strike Chance 1",
  "Enchantment Tornado Shot Critical Strike Chance 2",
  "Enchantment Tornado Shot Damage 1",
  "Enchantment Tornado Shot Damage 2",
  "Enchantment Tornado Shot Num Of Secondary Projectiles 1",
  "Enchantment Tornado Shot Num Of Secondary Projectiles 2",
  "Enchantment Toxic Rain Damage 1",
  "Enchantment Toxic Rain Damage 2",
  "Enchantment Toxic Rain Num Of Additional Projectiles 1",
  "Enchantment Toxic Rain Physical Added As Chaos 1",
  "Enchantment Toxic Rain Physical Added As Chaos 2",
  "Enchantment Vengeance Cooldown Speed 1",
  "Enchantment Vengeance Cooldown Speed 2",
  "Enchantment Vengeance Damage 1",
  "Enchantment Vengeance Damage 2",
  "Enchantment Vigilant Strike Damage 1",
  "Enchantment Vigilant Strike Damage 2",
  "Enchantment Vigilant Strike Fortify Duration 1",
  "Enchantment Vigilant Strike Fortify Duration 2",
  "Enchantment Viper Strike Critical Strike Chance 1",
  "Enchantment Viper Strike Critical Strike Chance 2",
  "Enchantment Viper Strike Damage 1",
  "Enchantment Viper Strike Damage 2",
  "Enchantment Viper Strike Poison Duration 1",
  "Enchantment Viper Strike Poison Duration 2",
  "Enchantment Vitality Mana Reservation 1",
  "Enchantment Vitality Mana Reservation 2",
  "Enchantment Volatile Dead Cast Speed 1",
  "Enchantment Volatile Dead Cast Speed 2",
  "Enchantment Volatile Dead Damage 1",
  "Enchantment Volatile Dead Damage 2",
  "Enchantment Volatile Dead Orbs 3",
  "Enchantment Vortex AoE On Frostbolt 1",
  "Enchantment Vortex AoE On Frostbolt 2",
  "Enchantment Vortex Cooldown Recovery 1",
  "Enchantment Vortex Cooldown Recovery 2",
  "Enchantment Vortex Damage 1",
  "Enchantment Vortex Damage 2",
  "Enchantment Vortex Duration 1",
  "Enchantment Vortex Duration 2",
  "Enchantment Vulnerability Curse Effect 1",
  "Enchantment Vulnerability Curse Effect 2",
  "Enchantment Vulnerability Duration 1",
  "Enchantment Vulnerability Duration 2",
  "Enchantment War Banner Effect 1",
  "Enchantment War Banner Effect 2",
  "Enchantment Warlords Mark Curse Effect 1",
  "Enchantment Warlords Mark Curse Effect 2",
  "Enchantment Warlords Mark Duration 1",
  "Enchantment Warlords Mark Duration 2",
  "Enchantment Wave Of Conviction Additional Enemy Resistance 1",
  "Enchantment Wave Of Conviction Additional Enemy Resistance 2",
  "Enchantment Wave Of Conviction Damage 1",
  "Enchantment Wave Of Conviction Damage 2",
  "Enchantment Wave Of Conviction Duration 1",
  "Enchantment Wave Of Conviction Duration 2",
  "Enchantment Whirling Blades Attack Speed 1",
  "Enchantment Whirling Blades Attack Speed 2",
  "Enchantment Whirling Blades Damage 1",
  "Enchantment Whirling Blades Damage 2",
  "Enchantment Wild Strike Damage 1",
  "Enchantment Wild Strike Damage 2",
  "Enchantment Wild Strike Num Of Additional Projectiles In Chain 1",
  "Enchantment Wild Strike Num Of Additional Projectiles In Chain 2",
  "Enchantment Wild Strike Area Of Effect 1",
  "Enchantment Wild Strike Area Of Effect 2",
  "Enchantment Winter Orb Damage 1",
  "Enchantment Winter Orb Damage 2",
  "Enchantment Wither Duration 1",
  "Enchantment Wither Duration 2",
  "Enchantment Wither Area Of Effect 1",
  "Enchantment Wither Area Of Effect 2",
  "Enchantment Wrath Mana Reservation 1",
  "Enchantment Wrath Mana Reservation 2",
  "Enchantment Zealotry Mana Reservation 1",
  "Enchantment Zealotry Mana Reservation 2",
  "Enchantment Zombie Attack Speed 1",
  "Enchantment Zombie Attack Speed 2",
  "Enchantment Zombie Elemental Resistances 1",
  "Enchantment Zombie Elemental Resistances 2",
  "Storm Brand Additional Chain Chance 1",
  "Storm Brand Additional Chain Chance 2",
  "Storm Brand Attached Target Lightning Penetration 1",
  "Storm Brand Attached Target Lightning Penetration 2"
];

const BASE_TYPES_AXES: string[] = [
  //One-Handed Axes
  "Rusted Hatchet",
  "Jade Hatchet",
  "Boarding Axe",
  "Cleaver",
  "Broad Axe",
  "Arming Axe",
  "Decorative Axe",
  "Spectral Axe",
  "Etched Hatchet",
  "Jasper Axe",
  "Tomahawk",
  "Wrist Chopper",
  "War Axe",
  "Chest Splitter",
  "Ceremonial Axe",
  "Wraith Axe",
  "Engraved Hatchet",
  "Karui Axe",
  "Siege Axe",
  "Reaver Axe",
  "Butcher Axe",
  "Vaal Hatchet",
  "Royal Axe",
  "Infernal Axe",
  "Runic Hatchet",

  //Two-Handed Axes
  "Stone Axe",
  "Jade Chopper",
  "Woodsplitter",
  "Poleaxe",
  "Double Axe",
  "Gilded Axe",
  "Shadow Axe",
  "Dagger Axe",
  "Jasper Chopper",
  "Timber Axe",
  "Headsman Axe",
  "Labrys",
  "Noble Axe",
  "Abyssal Axe",
  "Karui Chopper",
  "Talon Axe",
  "Sundering Axe",
  "Ezomyte Axe",
  "Vaal Axe",
  "Despot Axe",
  "Void Axe",
  "Fleshripper"
];

const BASE_TYPES_BOWS: string[] = [
  "Crude Bow",
  "Short Bow",
  "Long Bow",
  "Composite Bow",
  "Recurve Bow",
  "Bone Bow",
  "Royal Bow",
  "Death Bow",
  "Grove Bow",
  "Reflex Bow",
  "Decurve Bow",
  "Compound Bow",
  "Sniper Bow",
  "Ivory Bow",
  "Highborn Bow",
  "Decimation Bow",
  "Thicket Bow",
  "Steelwood Bow",
  "Citadel Bow",
  "Ranger Bow",
  "Assassin Bow",
  "Spine Bow",
  "Imperial Bow",
  "Harbinger Bow",
  "Maraketh Bow"
];

const BASE_TYPES_CLAWS: string[] = [
  "Nailed Fist",
  "Sharktooth Claw",
  "Awl",
  "Cat's Paw",
  "Blinder",
  "Timeworn Claw",
  "Sparkling Claw",
  "Fright Claw",
  "Double Claw",
  "Thresher Claw",
  "Gouger",
  "Tiger's Paw",
  "Gut Ripper",
  "Prehistoric Claw",
  "Noble Claw",
  "Eagle Claw",
  "Twin Claw",
  "Great White Claw",
  "Throat Stabber",
  "Hellion's Paw",
  "Eye Gouger",
  "Vaal Claw",
  "Imperial Claw",
  "Terror Claw",
  "Gemini Claw"
];

const BASE_TYPES_DAGGERS: string[] = [
  "Glass Shank",
  "Skinning Knife",
  "Carving Knife",
  "Stiletto",
  "Boot Knife",
  "Copper Kris",
  "Skean",
  "Flaying Knife",
  "Imp Dagger",
  "Prong Dagger",
  "Butcher Knife",
  "Poignard",
  "Boot Blade",
  "Golden Kris",
  "Royal Skean",
  "Trisula",
  "Fiend Dagger",
  "Gutting Knife",
  "Slaughter Knife",
  "Ambusher",
  "Ezomyte Dagger",
  "Platinum Kris",
  "Imperial Skean",
  "Demon Dagger",
  "Sai"
];

const BASE_TYPES_STAVES: string[] = [
  "Gnarled Branch",
  "Primitive Staff",
  "Iron Staff",
  "Long Staff",
  "Coiled Staff",
  "Royal Staff",
  "Vile Staff",
  "Crescent Staff",
  "Woodful Staff",
  "Military Staff",
  "Quarterstaff",
  "Serpentine Staff",
  "Highborn Staff",
  "Foul Staff",
  "Moon Staff",
  "Primordial Staff",
  "Ezomyte Staff",
  "Lathi",
  "Maelström Staff",
  "Imperial Staff",
  "Judgement Staff",
  "Eclipse Staff"
];

const BASE_TYPES_SWORDS: string[] = [
  //One-Handed Swords
  "Rusted Sword",
  "Copper Sword",
  "Sabre",
  "Broad Sword",
  "War Sword",
  "Ancient Sword",
  "Elegant Sword",
  "Dusk Blade",
  "Hook Sword",
  "Variscite Blade",
  "Cutlass",
  "Baselard",
  "Battle Sword",
  "Elder Sword",
  "Graceful Sword",
  "Twilight Blade",
  "Grappler",
  "Gemstone Sword",
  "Corsair Sword",
  "Gladius",
  "Legion Sword",
  "Vaal Blade",
  "Eternal Sword",
  "Midnight Blade",
  "Tiger Hook",

  //Thrusting One-Handed Swords
  "Rusted Spike",
  "Whalebone Rapier",
  "Battered Foil",
  "Basket Rapier",
  "Jagged Foil",
  "Antique Rapier",
  "Elegant Foil",
  "Thorn Rapier",
  "Smallsword",
  "Wyrmbone Rapier",
  "Burnished Foil",
  "Estoc",
  "Serrated Foil",
  "Primeval Rapier",
  "Fancy Foil",
  "Apex Rapier",
  "Courtesan Sword",
  "Dragonbone Rapier",
  "Tempered Foil",
  "Pecoraro",
  "Spiraled Foil",
  "Vaal Rapier",
  "Jewelled Foil",
  "Harpy Rapier",
  "Dragoon Sword",

  //Two-Handed Swords
  "Corroded Blade",
  "Longsword",
  "Bastard Sword",
  "Two-Handed Sword",
  "Etched Greatsword",
  "Ornate Sword",
  "Spectral Sword",
  "Curved Blade",
  "Butcher Sword",
  "Footman Sword",
  "Highland Blade",
  "Engraved Greatsword",
  "Tiger Sword",
  "Wraith Sword",
  "Lithe Blade",
  "Headman's Sword",
  "Reaver Sword",
  "Ezomyte Blade",
  "Vaal Greatsword",
  "Lion Sword",
  "Infernal Sword",
  "Exquisite Blade"
];

const BASE_TYPES_WANDS: string[] = [
  "Driftwood Wand",
  "Goat's Horn",
  "Carved Wand",
  "Quartz Wand",
  "Spiraled Wand",
  "Sage Wand",
  "Pagan Wand",
  "Faun's Horn",
  "Engraved Wand",
  "Crystal Wand",
  "Serpent Wand",
  "Omen Wand",
  "Heathen Wand",
  "Demon's Horn",
  "Imbued Wand",
  "Opal Wand",
  "Tornado Wand",
  "Prophecy Wand",
  "Profane Wand"
];

const BASE_TYPES_BODYS: string[] = [
  //Armour
  "Plate Vest",
  "Chestplate",
  "Copper Plate",
  "War Plate",
  "Full Plate",
  "Arena Plate",
  "Lordly Plate",
  "Bronze Plate",
  "Battle Plate",
  "Sun Plate",
  "Colosseum Plate",
  "Majestic Plate",
  "Golden Plate",
  "Crusader Plate",
  "Astral Plate",
  "Gladiator Plate",
  "Glorious Plate",

  //Evasion
  "Shabby Jerkin",
  "Strapped Leather",
  "Buckskin Tunic",
  "Wild Leather",
  "Full Leather",
  "Sun Leather",
  "Thief's Garb",
  "Eelskin Tunic",
  "Frontier Leather",
  "Glorious Leather",
  "Coronal Leather",
  "Cutthroat's Garb",
  "Sharkskin Tunic",
  "Destiny Leather",
  "Exquisite Leather",
  "Zodiac Leather",
  "Assassin's Garb",

  //Energy Shield
  "Simple Robe",
  "Silken Vest",
  "Scholar's Robe",
  "Silken Garb",
  "Mage's Vestment",
  "Silk Robe",
  "Cabalist Regalia",
  "Sage's Robe",
  "Silken Wrap",
  "Conjurer's Vestment",
  "Spidersilk Robe",
  "Destroyer Regalia",
  "Savant's Robe",
  "Necromancer Silks",
  "Occultist's Vestment",
  "Widowsilk Robe",
  "Vaal Regalia",

  //Armour/Evasion
  "Scale Vest",
  "Light Brigandine",
  "Scale Doublet",
  "Infantry Brigandine",
  "Full Scale Armour",
  "Soldier's Brigandine",
  "Field Lamellar",
  "Wyrmscale Doublet",
  "Hussar Brigandine",
  "Full Wyrmscale",
  "Commander's Brigandine",
  "Battle Lamellar",
  "Dragonscale Doublet",
  "Desert Brigandine",
  "Full Dragonscale",
  "General's Brigandine",
  "Triumphant Lamellar",

  //Armour/Energy Shield
  "Chainmail Vest",
  "Chainmail Tunic",
  "Ringmail Coat",
  "Chainmail Doublet",
  "Full Ringmail",
  "Full Chainmail",
  "Holy Chainmail",
  "Latticed Ringmail",
  "Crusader Chainmail",
  "Ornate Ringmail",
  "Chain Hauberk",
  "Devout Chainmail",
  "Loricated Ringmail",
  "Conquest Chainmail",
  "Elegant Ringmail",
  "Saint's Hauberk",
  "Saintly Chainmail",

  //Energy Shield/Evasion
  "Padded Vest",
  "Oiled Vest",
  "Padded Jacket",
  "Oiled Coat",
  "Scarlet Raiment",
  "Waxed Garb",
  "Bone Armour",
  "Quilted Jacket",
  "Sleek Coat",
  "Crimson Raiment",
  "Lacquered Garb",
  "Crypt Armour",
  "Sentinel Jacket",
  "Varnished Coat",
  "Blood Raiment",
  "Sadist Garb",
  "Carnal Armour"
];

const BASE_TYPES_BOOTS: string[] = [
  //Armour
  "Iron Greaves",
  "Steel Greaves",
  "Plated Greaves",
  "Reinforced Greaves",
  "Antique Greaves",
  "Ancient Greaves",
  "Goliath Greaves",
  "Vaal Greaves",
  "Titan Greaves",

  //Evasion
  "Rawhide Boots",
  "Goathide Boots",
  "Deerskin Boots",
  "Nubuck Boots",
  "Eelskin Boots",
  "Sharkskin Boots",
  "Shagreen Boots",
  "Stealth Boots",
  "Slink Boots",

  //Energy Shield
  "Wool Shoes",
  "Velvet Slippers",
  "Silk Slippers",
  "Scholar Boots",
  "Satin Slippers",
  "Samite Slippers",
  "Conjurer Boots",
  "Arcanist Slippers",
  "Sorcerer Boots",

  //Armour/Evasion
  "Leatherscale Boots",
  "Ironscale Boots",
  "Bronzescale Boots",
  "Steelscale Boots",
  "Serpentscale Boots",
  "Wyrmscale Boots",
  "Hydrascale Boots",
  "Dragonscale Boots",
  "Two-Toned Boots",

  //Armour/Energy Shield
  "Chain Boots",
  "Ringmail Boots",
  "Mesh Boots",
  "Riveted Boots",
  "Zealot Boots",
  "Soldier Boots",
  "Legion Boots",
  "Crusader Boots",
  "Two-Toned Boots",

  //Energy Shield/Evasion
  "Wrapped Boots",
  "Strapped Boots",
  "Clasped Boots",
  "Shackled Boots",
  "Trapper Boots",
  "Ambush Boots",
  "Carnal Boots",
  "Assassin's Boots",
  "Murder Boots",
  "Two-Toned Boots"
];

const BASE_TYPES_GLOVES: string[] = [
  //Armour
  "Iron Gauntlets",
  "Plated Gauntlets",
  "Bronze Gauntlets",
  "Steel Gauntlets",
  "Antique Gauntlets",
  "Ancient Gauntlets",
  "Goliath Gauntlets",
  "Vaal Gauntlets",
  "Titan Gauntlets",
  "Spiked Gloves",

  //Evasion
  "Rawhide Gloves",
  "Goathide Gloves",
  "Deerskin Gloves",
  "Nubuck Gloves",
  "Eelskin Gloves",
  "Sharkskin Gloves",
  "Shagreen Gloves",
  "Stealth Gloves",
  "Gripped Gloves",
  "Slink Gloves",

  //Energy Shield
  "Wool Gloves",
  "Velvet Gloves",
  "Silk Gloves",
  "Embroidered Gloves",
  "Satin Gloves",
  "Samite Gloves",
  "Conjurer Gloves",
  "Arcanist Gloves",
  "Sorcerer Gloves",
  "Fingerless Silk Gloves",

  //Armour/Evasion
  "Fishscale Gauntlets",
  "Ironscale Gauntlets",
  "Bronzescale Gauntlets",
  "Steelscale Gauntlets",
  "Serpentscale Gauntlets",
  "Wyrmscale Gauntlets",
  "Hydrascale Gauntlets",
  "Dragonscale Gauntlets",

  //Armour/Energy Shield
  "Chain Gloves",
  "Ringmail Gloves",
  "Mesh Gloves",
  "Riveted Gloves",
  "Zealot Gloves",
  "Soldier Gloves",
  "Legion Gloves",
  "Crusader Gloves",

  //Energy Shield/Evasion
  "Wrapped Mitts",
  "Strapped Mitts",
  "Clasped Mitts",
  "Trapper Mitts",
  "Ambush Mitts",
  "Carnal Mitts",
  "Assassin's Mitts",
  "Murder Mitts"
];

const BASE_TYPES_HELMETS: string[] = [
  //Armour
  "Iron Hat",
  "Cone Helmet",
  "Barbute Helmet",
  "Close Helmet",
  "Gladiator Helmet",
  "Reaver Helmet",
  "Siege Helmet",
  "Samite Helmet",
  "Ezomyte Burgonet",
  "Royal Burgonet",
  "Eternal Burgonet",

  //Evasion
  "Leather Cap",
  "Tricorne",
  "Leather Hood",
  "Wolf Pelt",
  "Hunter Hood",
  "Noble Tricorne",
  "Ursine Pelt",
  "Silken Hood",
  "Sinner Tricorne",
  "Lion Pelt",

  //Energy Shield
  "Vine Circlet",
  "Iron Circlet",
  "Torture Cage",
  "Tribal Circlet",
  "Bone Circlet",
  "Lunaris Circlet",
  "Steel Circlet",
  "Necromancer Circlet",
  "Solaris Circlet",
  "Mind Cage",
  "Hubris Circlet",

  //Armour/Evasion
  "Battered Helm",
  "Sallet",
  "Visored Sallet",
  "Gilded Sallet",
  "Secutor Helm",
  "Fencer Helm",
  "Lacquered Helmet",
  "Fluted Bascinet",
  "Pig-Faced Bascinet",
  "Nightmare Bascinet",

  //Armour/Energy Shield
  "Rusted Coif",
  "Soldier Helmet",
  "Great Helmet",
  "Crusader Helmet",
  "Aventail Helmet",
  "Zealot Helmet",
  "Great Crown",
  "Magistrate Crown",
  "Prophet Crown",
  "Praetor Crown",
  "Bone Helmet",

  //Energy Shield/Evasion
  "Scare Mask",
  "Plague Mask",
  "Iron Mask",
  "Festival Mask",
  "Golden Mask",
  "Raven Mask",
  "Callous Mask",
  "Regicide Mask",
  "Harlequin Mask",
  "Vaal Mask",
  "Deicide Mask"
];

const BASE_TYPES_SHIELDS: string[] = [
  //Armour
  "Splintered Tower Shield",
  "Corroded Tower Shield",
  "Rawhide Tower Shield",
  "Cedar Tower Shield",
  "Copper Tower Shield",
  "Reinforced Tower Shield",
  "Painted Tower Shield",
  "Buckskin Tower Shield",
  "Mahogany Tower Shield",
  "Bronze Tower Shield",
  "Girded Tower Shield",
  "Crested Tower Shield",
  "Shagreen Tower Shield",
  "Ebony Tower Shield",
  "Ezomyte Tower Shield",
  "Colossal Tower Shield",
  "Pinnacle Tower Shield",

  //Evasion
  "Goathide Buckler",
  "Pine Buckler",
  "Painted Buckler",
  "Hammered Buckler",
  "War Buckler",
  "Gilded Buckler",
  "Oak Buckler",
  "Enameled Buckler",
  "Corrugated Buckler",
  "Battle Buckler",
  "Golden Buckler",
  "Ironwood Buckler",
  "Lacquered Buckler",
  "Vaal Buckler",
  "Crusader Buckler",
  "Imperial Buckler",

  //Energy Shield
  "Twig Spirit Shield",
  "Yew Spirit Shield",
  "Bone Spirit Shield",
  "Tarnished Spirit Shield",
  "Jingling Spirit Shield",
  "Brass Spirit Shield",
  "Walnut Spirit Shield",
  "Ivory Spirit Shield",
  "Ancient Spirit Shield",
  "Chiming Spirit Shield",
  "Thorium Spirit Shield",
  "Lacewood Spirit Shield",
  "Fossilised Spirit Shield",
  "Vaal Spirit Shield",
  "Harmonic Spirit Shield",
  "Titanium Spirit Shield",

  //Armour/Evasion
  "Rotted Round Shield",
  "Fir Round Shield",
  "Studded Round Shield",
  "Scarlet Round Shield",
  "Splendid Round Shield",
  "Maple Round Shield",
  "Spiked Round Shield",
  "Crimson Round Shield",
  "Baroque Round Shield",
  "Teak Round Shield",
  "Spiny Round Shield",
  "Cardinal Round Shield",
  "Elegant Round Shield",

  //Armour/Energy Shield
  "Plank Kite Shield",
  "Linden Kite Shield",
  "Reinforced Kite Shield",
  "Layered Kite Shield",
  "Ceremonial Kite Shield",
  "Etched Kite Shield",
  "Steel Kite Shield",
  "Laminated Kite Shield",
  "Angelic Kite Shield",
  "Branded Kite Shield",
  "Champion Kite Shield",
  "Mosaic Kite Shield",
  "Archon Kite Shield",

  //Energy Shield/Evasion
  "Spiked Bundle",
  "Driftwood Spiked Shield",
  "Alloyed Spiked Shield",
  "Burnished Spiked Shield",
  "Ornate Spiked Shield",
  "Redwood Spiked Shield",
  "Compound Spiked Shield",
  "Polished Spiked Shield",
  "Sovereign Spiked Shield",
  "Alder Spiked Shield",
  "Ezomyte Spiked Shield",
  "Mirrored Spiked Shield",
  "Supreme Spiked Shield"
];

const BASE_TYPES_AMULETS: string[] = [
  //Regular
  "Coral Amulet",
  "Paua Amulet",
  "Amber Amulet",
  "Jade Amulet",
  "Lapis Amulet",
  "Gold Amulet",
  "Agate Amulet",
  "Citrine Amulet",
  "Turquoise Amulet",
  "Onyx Amulet",
  "Marble Amulet",
  "Blue Pearl Amulet",

  //Talismans
  "Ashscale Talisman",
  "Avian Twins Talisman",
  "Avian Twins Talisman",
  "Avian Twins Talisman",
  "Avian Twins Talisman",
  "Avian Twins Talisman",
  "Avian Twins Talisman",
  "Black Maw Talisman",
  "Bonespire Talisman",
  "Breakrib Talisman",
  "Chrysalis Talisman",
  "Clutching Talisman",
  "Deadhand Talisman",
  "Deep One Talisman",
  "Fangjaw Talisman",
  "Greatwolf Talisman",
  "Hexclaw Talisman",
  "Horned Talisman",
  "Lone Antler Talisman",
  "Longtooth Talisman",
  "Mandible Talisman",
  "Monkey Paw Talisman",
  "Monkey Paw Talisman",
  "Monkey Paw Talisman",
  "Monkey Twins Talisman",
  "Primal Skull Talisman",
  "Rot Head Talisman",
  "Rotfeather Talisman",
  "Spinefuse Talisman",
  "Splitnewt Talisman",
  "Three Hands Talisman",
  "Three Rat Talisman",
  "Undying Flesh Talisman",
  "Wereclaw Talisman",
  "Writhing Talisman"
];

const BASE_TYPES_BELTS: string[] = [
  "Chain Belt",
  "Rustic Sash",
  "Stygian Vise",
  "Heavy Belt",
  "Leather Belt",
  "Cloth Belt",
  "Studded Belt",
  "Vanguard Belt",
  "Crystal Belt"
];

const BASE_TYPES_QUIVERES: string[] = [
  "Two-Point Arrow Quiver",
  "Serrated Arrow Quiver",
  "Sharktooth Arrow Quiver",
  "Blunt Arrow Quiver",
  "Fire Arrow Quiver",
  "Broadhead Arrow Quiver",
  "Penetrating Arrow Quiver",
  "Ornate Quiver",
  "Spike-Point Arrow Quiver"
];

const BASE_TYPES_RINGS: string[] = [
  "Breach Ring",
  "Coral Ring",
  "Iron Ring",
  "Paua Ring",
  "Unset Ring",
  "Sapphire Ring",
  "Topaz Ring",
  "Ruby Ring",
  "Diamond Ring",
  "Gold Ring",
  "Moonstone Ring",
  "Two-Stone Ring",
  "Two-Stone Ring",
  "Two-Stone Ring",
  "Amethyst Ring",
  "Prismatic Ring",
  "Opal Ring",
  "Steel Ring"
];

const BASE_TYPES_JEWELS: string[] = [
  "Cobalt Jewel",
  "Crimson Jewel",
  "Viridian Jewel",
  "Ghastly Eye Jewel",
  "Hypnotic Eye Jewel",
  "Murderous Eye Jewel",
  "Searching Eye Jewel"
];

const BASE_TYPES_FLASKS: string[] = [
  "Small Life Flask",
  "Medium Life Flask",
  "Large Life Flask",
  "Greater Life Flask",
  "Grand Life Flask",
  "Giant Life Flask",
  "Colossal Life Flask",
  "Sacred Life Flask",
  "Hallowed Life Flask",
  "Sanctified Life Flask",
  "Divine Life Flask",
  "Eternal Life Flask",
  "Small Mana Flask",
  "Medium Mana Flask",
  "Large Mana Flask",
  "Greater Mana Flask",
  "Grand Mana Flask",
  "Giant Mana Flask",
  "Colossal Mana Flask",
  "Sacred Mana Flask",
  "Hallowed Mana Flask",
  "Sanctified Mana Flask",
  "Divine Mana Flask",
  "Eternal Mana Flask",
  "Small Hybrid Flask",
  "Medium Hybrid Flask",
  "Large Hybrid Flask",
  "Colossal Hybrid Flask",
  "Sacred Hybrid Flask",
  "Hallowed Hybrid Flask",
  "Quicksilver Flask",
  "Bismuth Flask",
  "Stibnite Flask",
  "Amethyst Flask",
  "Ruby Flask",
  "Sapphire Flask",
  "Topaz Flask",
  "Silver Flask",
  "Aquamarine Flask",
  "Granite Flask",
  "Jade Flask",
  "Quartz Flask",
  "Sulphur Flask",
  "Basalt Flask",
  "Diamond Flask"
];

const BASE_TYPES_CURRENCIES: string[] = [
  "Albino Rhoa Feather",
  "Apprentice Cartographer's Seal",
  "Apprentice Cartographer's Sextant",
  "Armourer's Scrap",
  "Bestiary Orb",
  "Blacksmith's Whetstone",
  "Blessed Orb",
  "Blessing of Chayula",
  "Blessing of Esh",
  "Blessing of Tul",
  "Blessing of Uul-Netol",
  "Blessing of Xoph",
  "Cartographer's Chisel",
  "Chaos Orb",
  "Chromatic Orb",
  "Divine Orb",
  "Exalted Orb",
  "Gemcutter's Prism",
  "Glassblower's Bauble",
  "Jeweller's Orb",
  "Journeyman Cartographer's Seal",
  "Journeyman Cartographer's Sextant",
  "Master Cartographer's Seal",
  "Master Cartographer's Sextant",
  "Mirror of Kalandra",
  "Orb of Alchemy",
  "Orb of Alteration",
  "Orb of Annulment",
  "Orb of Augmentation",
  "Orb of Chance",
  "Orb of Fusing",
  "Orb of Regret",
  "Orb of Scouring",
  "Orb of Transmutation",
  "Portal Scroll",
  "Regal Orb",
  "Scroll of Wisdom",
  "Silver Coin",
  "Stacked Deck",
  "Unshaping Orb",
  "Vaal Orb",
  "Vial of Awakening",
  "Vial of Consequence",
  "Vial of Dominance",
  "Vial of Fate",
  "Vial of Sacrifice",
  "Vial of Summoning",
  "Vial of the Ghost",
  "Vial of the Ritual",
  "Vial of Transcendence",
  "Bestiary Orb",
  "Reinforced Iron Net",
  "Reinforced Rope Net",
  "Reinforced Steel Net",
  "Simple Iron Net",
  "Simple Rope Net",
  "Simple Steel Net",
  "Strong Iron Net",
  "Strong Rope Net",
  "Strong Steel Net",
  "Thaumaturgical Net",
  "Ancient Orb"
];

const BASE_TYPES_FRAGMENTS: string[] = [
  "Alchemy Shard",
  "Alteration Shard",
  "Scroll Fragment",
  "Splinter of Chayula",
  "Splinter of Esh",
  "Splinter of Tul",
  "Splinter of Uul-Netol",
  "Splinter of Xoph",
  "Transmutation Shard",
  "Ancient Shard",
  "Annulment Shard",
  "Binding Shard",
  "Chaos Shard",
  "Engineer's Orb",
  "Engineer's Shard",
  "Exalted Shard",
  "Harbinger's Orb",
  "Harbinger's Shard",
  "Horizon Shard",
  "Mirror Shard",
  "Orb of Binding",
  "Orb of Horizons",
  "Regal Shard",
  "Perandus Coin",
  "Sacrifice at Dusk",
  "Sacrifice at Dawn",
  "Sacrifice at Noon",
  "Sacrifice at Midnight",
  "Mortal Grief",
  "Mortal Hope",
  "Mortal Ignorance",
  "Mortal Rage",
  "Volkuur's Key",
  "Eber's Key",
  "Yriel's Key",
  "Inya's Key",
  "Fragment of the Hydra",
  "Fragment of the Phoenix",
  "Fragment of the Minotaur",
  "Fragment of the Chimera",
  "Divine Vessel",
  "Gilded Ambush Scarab",
  "Gilded Bestiary Scarab",
  "Gilded Breach Scarab",
  "Gilded Cartography Scarab",
  "Gilded Divination Scarab",
  "Gilded Elder Scarab",
  "Gilded Harbinger Scarab",
  "Gilded Perandus Scarab",
  "Gilded Reliquary Scarab",
  "Gilded Shaper Scarab",
  "Gilded Sulphite Scarab",
  "Gilded Torment Scarab",
  "Polished Ambush Scarab",
  "Polished Bestiary Scarab",
  "Polished Breach Scarab",
  "Polished Cartography Scarab",
  "Polished Divination Scarab",
  "Polished Elder Scarab",
  "Polished Harbinger Scarab",
  "Polished Perandus Scarab",
  "Polished Reliquary Scarab",
  "Polished Shaper Scarab",
  "Polished Sulphite Scarab",
  "Polished Torment Scarab",
  "Rusted Ambush Scarab",
  "Rusted Bestiary Scarab",
  "Rusted Breach Scarab",
  "Rusted Cartography Scarab",
  "Rusted Divination Scarab",
  "Rusted Elder Scarab",
  "Rusted Harbinger Scarab",
  "Rusted Perandus Scarab",
  "Rusted Reliquary Scarab",
  "Rusted Shaper Scarab",
  "Rusted Sulphite Scarab",
  "Rusted Torment Scarab"
];

const BASE_TYPES_ESSENCES: string[] = [
  "Muttering Essence of Anger",
  "Weeping Essence of Anger",
  "Wailing Essence of Anger",
  "Screaming Essence of Anger",
  "Shrieking Essence of Anger",
  "Deafening Essence of Anger",
  "Wailing Essence of Anguish",
  "Screaming Essence of Anguish",
  "Shrieking Essence of Anguish",
  "Deafening Essence of Anguish",
  "Whispering Essence of Contempt",
  "Muttering Essence of Contempt",
  "Weeping Essence of Contempt",
  "Wailing Essence of Contempt",
  "Screaming Essence of Contempt",
  "Shrieking Essence of Contempt",
  "Deafening Essence of Contempt",
  "Essence of Delirium",
  "Weeping Essence of Doubt",
  "Wailing Essence of Doubt",
  "Screaming Essence of Doubt",
  "Shrieking Essence of Doubt",
  "Deafening Essence of Doubt",
  "Screaming Essence of Dread",
  "Shrieking Essence of Dread",
  "Deafening Essence of Dread",
  "Screaming Essence of Envy",
  "Shrieking Essence of Envy",
  "Deafening Essence of Envy",
  "Muttering Essence of Fear",
  "Weeping Essence of Fear",
  "Wailing Essence of Fear",
  "Screaming Essence of Fear",
  "Shrieking Essence of Fear",
  "Deafening Essence of Fear",
  "Whispering Essence of Greed",
  "Muttering Essence of Greed",
  "Weeping Essence of Greed",
  "Wailing Essence of Greed",
  "Screaming Essence of Greed",
  "Shrieking Essence of Greed",
  "Deafening Essence of Greed",
  "Whispering Essence of Hatred",
  "Muttering Essence of Hatred",
  "Weeping Essence of Hatred",
  "Wailing Essence of Hatred",
  "Screaming Essence of Hatred",
  "Shrieking Essence of Hatred",
  "Deafening Essence of Hatred",
  "Essence of Horror",
  "Essence of Hysteria",
  "Essence of Insanity",
  "Wailing Essence of Loathing",
  "Screaming Essence of Loathing",
  "Shrieking Essence of Loathing",
  "Deafening Essence of Loathing",
  "Screaming Essence of Misery",
  "Shrieking Essence of Misery",
  "Deafening Essence of Misery",
  "Weeping Essence of Rage",
  "Wailing Essence of Rage",
  "Screaming Essence of Rage",
  "Shrieking Essence of Rage",
  "Deafening Essence of Rage",
  "Screaming Essence of Scorn",
  "Shrieking Essence of Scorn",
  "Deafening Essence of Scorn",
  "Muttering Essence of Sorrow",
  "Weeping Essence of Sorrow",
  "Wailing Essence of Sorrow",
  "Screaming Essence of Sorrow",
  "Shrieking Essence of Sorrow",
  "Deafening Essence of Sorrow",
  "Wailing Essence of Spite",
  "Screaming Essence of Spite",
  "Shrieking Essence of Spite",
  "Deafening Essence of Spite",
  "Weeping Essence of Suffering",
  "Wailing Essence of Suffering",
  "Screaming Essence of Suffering",
  "Shrieking Essence of Suffering",
  "Deafening Essence of Suffering",
  "Muttering Essence of Torment",
  "Weeping Essence of Torment",
  "Wailing Essence of Torment",
  "Screaming Essence of Torment",
  "Shrieking Essence of Torment",
  "Deafening Essence of Torment",
  "Whispering Essence of Woe",
  "Muttering Essence of Woe",
  "Weeping Essence of Woe",
  "Wailing Essence of Woe",
  "Screaming Essence of Woe",
  "Shrieking Essence of Woe",
  "Deafening Essence of Woe",
  "Weeping Essence of Wrath",
  "Wailing Essence of Wrath",
  "Screaming Essence of Wrath",
  "Shrieking Essence of Wrath",
  "Deafening Essence of Wrath",
  "Wailing Essence of Zeal",
  "Screaming Essence of Zeal",
  "Shrieking Essence of Zeal",
  "Deafening Essence of Zeal"
]

const BASE_TYPES_FOSSILS: string[] = [
  "Aberrant Fossil",
  "Aetheric Fossil",
  "Bloodstained Fossil",
  "Bound Fossil",
  "Corroded Fossil",
  "Dense Fossil",
  "Enchanted Fossil",
  "Encrusted Fossil",
  "Faceted Fossil",
  "Fractured Fossil",
  "Frigid Fossil",
  "Gilded Fossil",
  "Glyphic Fossil",
  "Hollow Fossil",
  "Jagged Fossil",
  "Lucent Fossil",
  "Metallic Fossil",
  "Perfect Fossil",
  "Prismatic Fossil",
  "Pristine Fossil",
  "Sanctified Fossil",
  "Scorched Fossil",
  "Serrated Fossil",
  "Shuddering Fossil",
  "Tangled Fossil",
  "Potent Alchemical Resonator",
  "Potent Chaotic Resonator",
  "Powerful Alchemical Resonator",
  "Powerful Chaotic Resonator",
  "Prime Alchemical Resonator",
  "Prime Chaotic Resonator",
  "Primitive Alchemical Resonator",
  "Primitive Chaotic Resonator"
];

export const BASE_TYPES = [].concat(
  BASE_TYPES_AXES,
  BASE_TYPES_BOWS,
  BASE_TYPES_CLAWS,
  BASE_TYPES_DAGGERS,
  BASE_TYPES_STAVES,
  BASE_TYPES_SWORDS,
  BASE_TYPES_WANDS,
  BASE_TYPES_BODYS,
  BASE_TYPES_BOOTS,
  BASE_TYPES_GLOVES,
  BASE_TYPES_HELMETS,
  BASE_TYPES_SHIELDS,
  BASE_TYPES_AMULETS,
  BASE_TYPES_BELTS,
  BASE_TYPES_QUIVERES,
  BASE_TYPES_RINGS,
  BASE_TYPES_JEWELS,
  BASE_TYPES_FLASKS,
  BASE_TYPES_CURRENCIES,
  BASE_TYPES_FRAGMENTS,
  BASE_TYPES_ESSENCES,
  BASE_TYPES_FOSSILS
);
